/**
 * Official import-templates registry for Pilot / new academic delivery flow.
 * Source of truth for UI visibility, classification, and suggested filenames.
 * Commit path remains TEMPLATES + commit_import_job_atomic — this module does not invent columns.
 */

import type { ImportEntity } from "./types";

/** Contract version embedded in generated workbooks. */
export const IMPORT_CONTRACT_VERSION = "1.0.0";

export type EntityFlowClass =
  | "ACTIVE_NEW_FLOW"
  | "LEGACY_ONLY"
  | "GENERATED_NOT_IMPORTED"
  | "DEPRECATED"
  | "UNSAFE"
  | "MISSING_TEMPLATE"
  | "MISSING_VALIDATOR"
  | "CONTRACT_MISMATCH"
  | "UI_MANAGED_NOT_IMPORTED"
  | "CATALOG_DOWNLOAD_ONLY";

export interface OfficialImportEntityMeta {
  entity: ImportEntity;
  classification: EntityFlowClass;
  /** Shown in /import dropdown */
  showInImportUi: boolean;
  label: string;
  group: string;
  description: string;
  /** Human-readable dependencies before this entity */
  dependsOn: string[];
  /** Filename stem without study_system / context suffixes */
  fileStem: string;
  /** Whether filename may include study_system context */
  studySystemScoped: boolean;
  targetTables: string[];
  naturalKey: string;
  commitRpc: "commit_import_job_atomic";
}

/** Entities that appear in the operational import UI (Pilot new flow). */
export const ACTIVE_NEW_FLOW_ENTITIES: ImportEntity[] = [
  "departments",
  "academic_programs",
  "academic_terms",
  "instructors",
  "rooms",
  "daily_breaks",
  "full_study_plan",
  "study_plan_courses",
  "course_programs",
  "academic_cohorts",
  "elective_slot_courses",
  "cohort_elective_selections",
  "teaching_assignments_v2",
];

/** Kept in TEMPLATES + SQL dispatcher for Legacy compatibility; hidden from new-flow UI. */
export const LEGACY_ONLY_ENTITIES: ImportEntity[] = [
  "sections",
  "course_offerings",
  "teaching_assignments",
  "section_groups",
];

/** Generated by system RPCs / schedule builder — never imported in Pilot. */
export const GENERATED_NOT_IMPORTED = [
  "delivery_groups",
  "cohort_curriculum",
  "course_offerings_v2_generated",
  "schedule_versions",
  "schedule_sessions",
  "published_schedules",
] as const;

/** Official Pilot study systems (regular/parallel fully isolated). */
export const PILOT_STUDY_SYSTEMS = ["regular", "parallel"] as const;

/** Schema-allowed cohort study_system values (broader than Pilot templates). */
export const SCHEMA_COHORT_STUDY_SYSTEMS = [
  "regular",
  "parallel",
  "evening",
  "distance",
  "other",
] as const;

/** Assignable component types for teaching_assignments_v2 (summer_training forbidden). */
export const TA_V2_COMPONENT_TYPES = ["theory", "practical", "tutorial", "project"] as const;

export const OFFICIAL_IMPORT_ORDER: {
  step: number;
  entity?: ImportEntity;
  label: string;
  kind: "import" | "ui" | "generate" | "note";
  notes?: string;
}[] = [
  {
    step: 1,
    label: "الكليات",
    kind: "ui",
    notes: "تُدار الكلية من الواجهة.",
  },
  {
    step: 1.1,
    entity: "departments",
    label: "الأقسام الأكاديمية",
    kind: "import",
  },
  {
    step: 1.2,
    entity: "academic_programs",
    label: "البرامج الأكاديمية",
    kind: "import",
    notes: "تتطلب أقسامًا تابعة للكلية المحددة.",
  },
  {
    step: 2,
    entity: "academic_terms",
    label: "الفصول الأكاديمية",
    kind: "import",
  },
  {
    step: 3,
    entity: "full_study_plan",
    label: "الخطة الدراسية الكاملة (+ مقررات/محاضرات)",
    kind: "import",
    notes: "study_plan_courses بديل لمستوى/فصل واحد.",
  },
  {
    step: 4,
    entity: "course_programs",
    label: "ربط المقررات المشتركة بالبرامج",
    kind: "import",
  },
  {
    step: 5,
    entity: "instructors",
    label: "المحاضرون",
    kind: "import",
  },
  {
    step: 6,
    entity: "rooms",
    label: "القاعات والمعامل",
    kind: "import",
  },
  {
    step: 7,
    entity: "daily_breaks",
    label: "الاستراحات اليومية",
    kind: "import",
  },
  {
    step: 8,
    label: "سياسات النصاب / التوفر / قوالب الفترات",
    kind: "ui",
    notes: "faculty_workload_policies و instructor_availability و time_slot_templates من الواجهة.",
  },
  {
    step: 9,
    entity: "academic_cohorts",
    label: "الدفعات الأكاديمية",
    kind: "import",
  },
  {
    step: 10,
    entity: "elective_slot_courses",
    label: "مقررات الخانات الاختيارية",
    kind: "import",
  },
  {
    step: 11,
    entity: "cohort_elective_selections",
    label: "اختيارات الدفعات الاختيارية",
    kind: "import",
  },
  {
    step: 12,
    label: "توليد منهج الدفعة (cohort curriculum)",
    kind: "generate",
    notes: "RPC generate_cohort_curriculum — ليس استيراد Excel.",
  },
  {
    step: 13,
    label: "توليد مجموعات التقديم (delivery groups)",
    kind: "generate",
    notes: "RPC generate_cohort_delivery_groups — ليس استيراد Excel.",
  },
  {
    step: 14,
    entity: "teaching_assignments_v2",
    label: "الإسناد التدريسي V2",
    kind: "import",
    notes: "يتطلب delivery_groups مولَّدة مسبقًا.",
  },
  {
    step: 15,
    label: "محرر الجدول (schedule builder)",
    kind: "note",
    notes: "schedule_versions / schedule_sessions تُنشأ من النظام — لا تُستورد في Pilot.",
  },
];

const META: Record<ImportEntity, OfficialImportEntityMeta> = {
  departments: {
    entity: "departments",
    classification: "ACTIVE_NEW_FLOW",
    showInImportUi: true,
    label: "الأقسام الأكاديمية",
    group: "بيانات أكاديمية",
    description: "تعريف أقسام الكلية المحددة قبل البرامج.",
    dependsOn: ["كلية محددة"],
    fileStem: "departments",
    studySystemScoped: false,
    targetTables: ["departments"],
    naturalKey: "code ثم الاسم داخل الكلية",
    commitRpc: "commit_import_job_atomic",
  },
  academic_programs: {
    entity: "academic_programs",
    classification: "ACTIVE_NEW_FLOW",
    showInImportUi: true,
    label: "البرامج الأكاديمية",
    group: "بيانات أكاديمية",
    description: "تعريف برامج الكلية وربطها بأقسامها.",
    dependsOn: ["أقسام الكلية المحددة"],
    fileStem: "academic_programs",
    studySystemScoped: false,
    targetTables: ["academic_programs"],
    naturalKey: "code ثم الاسم داخل القسم والكلية",
    commitRpc: "commit_import_job_atomic",
  },
  academic_terms: {
    entity: "academic_terms",
    classification: "ACTIVE_NEW_FLOW",
    showInImportUi: true,
    label: "الفصول الأكاديمية",
    group: "بيانات أكاديمية",
    description: "الفصل الأول أو الثاني ضمن العام الأكاديمي.",
    dependsOn: ["كلية نشطة"],
    fileStem: "academic_terms",
    studySystemScoped: false,
    targetTables: ["academic_terms"],
    naturalKey: "code",
    commitRpc: "commit_import_job_atomic",
  },
  instructors: {
    entity: "instructors",
    classification: "ACTIVE_NEW_FLOW",
    showInImportUi: true,
    label: "المحاضرون",
    group: "موارد",
    description: "بيانات المحاضرين وأنواع التوظيف والحدود الأسبوعية.",
    dependsOn: ["أقسام (اختياري لنوع/قسم)"],
    fileStem: "instructors",
    studySystemScoped: false,
    targetTables: ["instructors"],
    naturalKey: "employee_number",
    commitRpc: "commit_import_job_atomic",
  },
  rooms: {
    entity: "rooms",
    classification: "ACTIVE_NEW_FLOW",
    showInImportUi: true,
    label: "القاعات والمعامل",
    group: "موارد",
    description: "الأماكن المادية المستخدمة لتقديم المحاضرات والتطبيقات.",
    dependsOn: ["مبانٍ أكاديمية (اختياري)"],
    fileStem: "rooms",
    studySystemScoped: false,
    targetTables: ["rooms"],
    naturalKey: "code",
    commitRpc: "commit_import_job_atomic",
  },
  daily_breaks: {
    entity: "daily_breaks",
    classification: "ACTIVE_NEW_FLOW",
    showInImportUi: true,
    label: "الاستراحات اليومية",
    group: "موارد",
    description: "فترات الاستراحة التي تؤثر على توليد أوقات الجدولة.",
    dependsOn: [],
    fileStem: "daily_breaks",
    studySystemScoped: false,
    targetTables: ["daily_breaks"],
    naturalKey: "name",
    commitRpc: "commit_import_job_atomic",
  },
  full_study_plan: {
    entity: "full_study_plan",
    classification: "ACTIVE_NEW_FLOW",
    showInImportUi: true,
    label: "خطة دراسية كاملة",
    group: "بيانات أكاديمية",
    description: "استيراد الخطة الأكاديمية الكاملة مع محاضرات المقررات والخانات الاختيارية.",
    dependsOn: ["برامج", "أقسام"],
    fileStem: "full_study_plan",
    studySystemScoped: false,
    targetTables: [
      "study_plans",
      "academic_levels",
      "courses",
      "plan_courses",
      "plan_course_components",
      "elective_slots",
    ],
    naturalKey: "program_code|plan_code|plan_version|course_code",
    commitRpc: "commit_import_job_atomic",
  },
  study_plan_courses: {
    entity: "study_plan_courses",
    classification: "ACTIVE_NEW_FLOW",
    showInImportUi: true,
    label: "الخطط الدراسية (مستوى/فصل)",
    group: "بيانات أكاديمية",
    description: "مقررات الخطة حسب المستوى والفصل.",
    dependsOn: ["برامج", "أقسام"],
    fileStem: "study_plan_courses",
    studySystemScoped: false,
    targetTables: [
      "study_plans",
      "academic_levels",
      "courses",
      "plan_courses",
      "plan_course_components",
      "elective_slots",
    ],
    naturalKey: "program_code|plan_code|plan_version|course_code",
    commitRpc: "commit_import_job_atomic",
  },
  course_programs: {
    entity: "course_programs",
    classification: "ACTIVE_NEW_FLOW",
    showInImportUi: true,
    label: "ربط المقررات بالبرامج",
    group: "بيانات أكاديمية",
    description: "ربط المقررات المشتركة بالبرامج.",
    dependsOn: ["مقررات", "برامج"],
    fileStem: "course_programs",
    studySystemScoped: false,
    targetTables: ["course_programs"],
    naturalKey: "course_code|program_code",
    commitRpc: "commit_import_job_atomic",
  },
  academic_cohorts: {
    entity: "academic_cohorts",
    classification: "ACTIVE_NEW_FLOW",
    showInImportUi: true,
    label: "الدفعات الأكاديمية (V2)",
    group: "نموذج التقديم V2",
    description: "دفعات البرنامج/المستوى/نظام الدراسة للفصل المستهدف. لا تستخدم الشعب.",
    dependsOn: ["برامج", "مستويات", "فصول أكاديمية"],
    fileStem: "academic_cohorts",
    studySystemScoped: true,
    targetTables: ["academic_cohorts"],
    naturalKey: "program|level|study_system|entry_year|term",
    commitRpc: "commit_import_job_atomic",
  },
  elective_slot_courses: {
    entity: "elective_slot_courses",
    classification: "ACTIVE_NEW_FLOW",
    showInImportUi: true,
    label: "مقررات الخانات الاختيارية (V2)",
    group: "نموذج التقديم V2",
    description: "المقررات المسموح اختيارها داخل خانة اختيارية (على مستوى الخطة).",
    dependsOn: ["خطة دراسية", "خانات اختيارية", "مقررات"],
    fileStem: "elective_slot_courses",
    studySystemScoped: false,
    targetTables: ["elective_slot_courses"],
    naturalKey: "plan_code|elective_slot_code|course_code",
    commitRpc: "commit_import_job_atomic",
  },
  cohort_elective_selections: {
    entity: "cohort_elective_selections",
    classification: "ACTIVE_NEW_FLOW",
    showInImportUi: true,
    label: "اختيارات الدفعات (V2)",
    group: "نموذج التقديم V2",
    description: "المقرر المختار لكل دفعة وخانة — لا تسجيل فردي للطالب.",
    dependsOn: ["academic_cohorts", "elective_slot_courses"],
    fileStem: "cohort_elective_selections",
    studySystemScoped: true,
    targetTables: ["cohort_elective_selections"],
    naturalKey: "cohort_code|elective_slot_code",
    commitRpc: "commit_import_job_atomic",
  },
  teaching_assignments_v2: {
    entity: "teaching_assignments_v2",
    classification: "ACTIVE_NEW_FLOW",
    showInImportUi: true,
    label: "الإسناد التدريسي V2",
    group: "نموذج التقديم V2",
    description: "إسناد محاضر لدفعة + مقرر + محاضرة + مجموعة تقديم. بدون section_id.",
    dependsOn: ["academic_cohorts", "delivery_groups (مولَّدة)", "instructors", "محاضرات الخطة"],
    fileStem: "teaching_assignments_v2",
    studySystemScoped: true,
    targetTables: ["teaching_assignments"],
    naturalKey: "cohort|course|component|delivery_group|employee",
    commitRpc: "commit_import_job_atomic",
  },
  sections: {
    entity: "sections",
    classification: "LEGACY_ONLY",
    showInImportUi: false,
    label: "المجموعات الدراسية (Legacy)",
    group: "Legacy",
    description: "توافق قديم فقط — لا يظهر في مسار التشغيل الجديد.",
    dependsOn: ["terms", "courses"],
    fileStem: "sections_legacy",
    studySystemScoped: true,
    targetTables: ["sections"],
    naturalKey: "term|course|section_number|study_system",
    commitRpc: "commit_import_job_atomic",
  },
  course_offerings: {
    entity: "course_offerings",
    classification: "LEGACY_ONLY",
    showInImportUi: false,
    label: "إسناد المقررات (Legacy)",
    group: "Legacy",
    description: "في المسار الجديد تُولَّد العروض من منهج الدفعة — لا تُستورد تشغيلًا.",
    dependsOn: ["terms", "courses"],
    fileStem: "course_offerings_legacy",
    studySystemScoped: false,
    targetTables: ["course_offerings"],
    naturalKey: "term|course|program",
    commitRpc: "commit_import_job_atomic",
  },
  teaching_assignments: {
    entity: "teaching_assignments",
    classification: "LEGACY_ONLY",
    showInImportUi: false,
    label: "الإسناد التدريسي V1 (Legacy)",
    group: "Legacy",
    description: "يعتمد section_number/session_type — استخدم teaching_assignments_v2.",
    dependsOn: ["course_offerings", "instructors"],
    fileStem: "teaching_assignments_v1_legacy",
    studySystemScoped: false,
    targetTables: ["teaching_assignments"],
    naturalKey: "term|course|employee|session_type|section",
    commitRpc: "commit_import_job_atomic",
  },
  section_groups: {
    entity: "section_groups",
    classification: "LEGACY_ONLY",
    showInImportUi: false,
    label: "المجموعات المدمجة (Legacy)",
    group: "Legacy",
    description: "يعتمد أقسام sections — مخفي من واجهة التشغيل الجديد.",
    dependsOn: ["sections"],
    fileStem: "section_groups_legacy",
    studySystemScoped: false,
    targetTables: ["section_groups", "section_group_members"],
    naturalKey: "term|course|group_name",
    commitRpc: "commit_import_job_atomic",
  },
};

export function getEntityMeta(entity: ImportEntity): OfficialImportEntityMeta {
  return META[entity];
}

export function listImportUiEntities(): OfficialImportEntityMeta[] {
  return ACTIVE_NEW_FLOW_ENTITIES.map((e) => META[e]);
}

export function classifyEntity(entity: ImportEntity): EntityFlowClass {
  return META[entity].classification;
}

/**
 * Suggested download filename. Context is optional college / year / term suffix.
 * Naming is documentation only — validation uses in-file columns, not the filename.
 */
export function suggestedTemplateFilename(
  entity: ImportEntity,
  opts?: { studySystem?: string; context?: string; collegeCode?: string },
): string {
  const meta = META[entity];
  const parts: string[] = [meta.fileStem];
  if (meta.studySystemScoped && opts?.studySystem) {
    parts.push(opts.studySystem);
  }
  if (opts?.context) parts.push(opts.context);
  else if (opts?.collegeCode && !meta.studySystemScoped) {
    parts.push(`college-${opts.collegeCode.toLowerCase()}`);
  }
  return `${parts.join("_")}.xlsx`;
}

/** All ImportEntity keys known to the registry (for harness coverage checks). */
export function listRegisteredEntities(): ImportEntity[] {
  return Object.keys(META) as ImportEntity[];
}
