CREATE ROLE anon;
CREATE ROLE authenticated;
CREATE SCHEMA auth;
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
GRANT USAGE ON SCHEMA auth TO authenticated,anon;
CREATE TYPE public.app_role AS ENUM('super_admin','college_admin','read_only','institutional_viewer');
CREATE TABLE user_roles(user_id uuid,role app_role);
CREATE TABLE user_colleges(user_id uuid,college_id uuid);
CREATE TABLE colleges(id uuid PRIMARY KEY,name text);
CREATE TABLE academic_terms(id uuid,college_id uuid,name text,academic_year text,term_type text,start_date date);
CREATE TABLE departments(id uuid,college_id uuid);
CREATE TABLE academic_programs(id uuid,college_id uuid);
CREATE TABLE plan_course_components(id uuid,component_type text,counts_toward_regular_load boolean);
CREATE TABLE instructors(id uuid,college_id uuid,academic_rank text,max_weekly_hours integer,administrative_release_hours integer,is_active boolean);
CREATE TABLE faculty_identities(id uuid,issuing_college_id uuid);
CREATE TABLE faculty_identity_links(identity_id uuid,instructor_id uuid);
CREATE TABLE faculty_workload_policies(college_id uuid,rank_code text,rank_aliases text[],required_load_hours numeric,active boolean);
CREATE TABLE schedule_versions(id uuid,college_id uuid,academic_term_id uuid,name text,status text,disposable_test boolean DEFAULT false,is_coordination boolean DEFAULT false,created_at timestamptz,updated_at timestamptz);
CREATE TABLE schedule_sessions(id uuid,college_id uuid,schedule_version_id uuid,plan_course_component_id uuid,session_type text,start_time time,end_time time,replaced_by_split boolean DEFAULT false,room_id uuid);
CREATE TABLE room_types(id uuid,code text);
CREATE TABLE rooms(id uuid,college_id uuid,room_type_id uuid,room_type text,capacity integer,is_active boolean);
CREATE TABLE workspace_fixture(college_id uuid,term_id uuid,payload jsonb);
CREATE FUNCTION has_role(u uuid,r app_role) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$SELECT EXISTS(SELECT 1 FROM user_roles WHERE user_id=u AND role=r)$$;
CREATE FUNCTION is_super_admin(u uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$SELECT has_role(u,'super_admin')$$;
CREATE FUNCTION user_in_college(u uuid,c uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$SELECT EXISTS(SELECT 1 FROM user_colleges WHERE user_id=u AND college_id=c)$$;
CREATE FUNCTION can_manage_college(u uuid,c uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$SELECT is_super_admin(u) OR (has_role(u,'college_admin') AND user_in_college(u,c))$$;
CREATE FUNCTION can_view_college(_user_id uuid,_college_id uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$SELECT is_super_admin(_user_id) OR user_in_college(_user_id,_college_id)$$;
CREATE FUNCTION list_teaching_assignment_workspace(p_college_id uuid,p_term_id uuid) RETURNS jsonb LANGUAGE sql STABLE AS $$SELECT jsonb_build_object('ok',true,'rows',coalesce((SELECT payload FROM workspace_fixture WHERE college_id=p_college_id AND term_id=p_term_id),'[]'))$$;
ALTER TABLE colleges ENABLE ROW LEVEL SECURITY;
CREATE POLICY col_select ON colleges FOR SELECT TO authenticated USING(can_view_college(auth.uid(),id));
ALTER TABLE rooms ENABLE ROW LEVEL SECURITY;
CREATE POLICY room_read ON rooms FOR SELECT TO authenticated USING(can_view_college(auth.uid(),college_id));
CREATE POLICY room_write ON rooms FOR ALL TO authenticated USING(can_manage_college(auth.uid(),college_id)) WITH CHECK(can_manage_college(auth.uid(),college_id));
ALTER TABLE user_roles ENABLE ROW LEVEL SECURITY;
CREATE POLICY role_read ON user_roles FOR SELECT TO authenticated USING(user_id=auth.uid() OR is_super_admin(auth.uid()));
CREATE POLICY role_write ON user_roles FOR ALL TO authenticated USING(is_super_admin(auth.uid())) WITH CHECK(is_super_admin(auth.uid()));
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA public TO authenticated;
