/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as VerifyReportRouteImport } from './routes/verify-report'
import { Route as AuthenticatedAcademicCalendarRouteImport } from './routes/_authenticated/academic-calendar'
import { Route as AuthenticatedAcademicCohortsRouteImport } from './routes/_authenticated/academic-cohorts'
import { Route as AuthenticatedAccountSecurityRouteImport } from './routes/_authenticated/account-security'
import { Route as AuthenticatedAdminToolsRouteImport } from './routes/_authenticated/admin-tools'
import { Route as AuthenticatedAutoScheduleRouteImport } from './routes/_authenticated/auto-schedule'
import { Route as AuthenticatedAvailabilityRouteImport } from './routes/_authenticated/availability'
import { Route as AuthenticatedBuildingsRouteImport } from './routes/_authenticated/buildings'
import { Route as AuthenticatedCollegesRouteImport } from './routes/_authenticated/colleges'
import { Route as AuthenticatedConflictChecksRouteImport } from './routes/_authenticated/conflict-checks'
import { Route as AuthenticatedConstraintSettingsRouteImport } from './routes/_authenticated/constraint-settings'
import { Route as AuthenticatedCourseOfferingsRouteImport } from './routes/_authenticated/course-offerings'
import { Route as AuthenticatedCoursesRouteImport } from './routes/_authenticated/courses'
import { Route as AuthenticatedDailyBreaksRouteImport } from './routes/_authenticated/daily-breaks'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDataCleanupRouteImport } from './routes/_authenticated/data-cleanup'
import { Route as AuthenticatedDataOnboardingRouteImport } from './routes/_authenticated/data-onboarding'
import { Route as AuthenticatedDataReadinessRouteImport } from './routes/_authenticated/data-readiness'
import { Route as AuthenticatedDataTemplatesRouteImport } from './routes/_authenticated/data-templates'
import { Route as AuthenticatedDeliveryGroupsRouteImport } from './routes/_authenticated/delivery-groups'
import { Route as AuthenticatedDepartmentsRouteImport } from './routes/_authenticated/departments'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedImportHistoryRouteImport } from './routes/_authenticated/import-history'
import { Route as AuthenticatedImportTemplatesRouteImport } from './routes/_authenticated/import-templates'
import { Route as AuthenticatedInstructorTypesRouteImport } from './routes/_authenticated/instructor-types'
import { Route as AuthenticatedInstructorsRouteImport } from './routes/_authenticated/instructors'
import { Route as AuthenticatedItcsCutoverRouteImport } from './routes/_authenticated/itcs-cutover'
import { Route as AuthenticatedItcsReviewProposalRouteImport } from './routes/_authenticated/itcs-review-proposal'
import { Route as AuthenticatedMyCollegeRouteImport } from './routes/_authenticated/my-college'
import { Route as AuthenticatedProgramsRouteImport } from './routes/_authenticated/programs'
import { Route as AuthenticatedPublishedSchedulesRouteImport } from './routes/_authenticated/published-schedules'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedRoomTypesRouteImport } from './routes/_authenticated/room-types'
import { Route as AuthenticatedRoomsRouteImport } from './routes/_authenticated/rooms'
import { Route as AuthenticatedScheduleBuilderRouteImport } from './routes/_authenticated/schedule-builder'
import { Route as AuthenticatedScheduleQualityRouteImport } from './routes/_authenticated/schedule-quality'
import { Route as AuthenticatedScheduleVersionsRouteImport } from './routes/_authenticated/schedule-versions'
import { Route as AuthenticatedSchedulingHeadcountsRouteImport } from './routes/_authenticated/scheduling-headcounts'
import { Route as AuthenticatedSchedulingSettingsRouteImport } from './routes/_authenticated/scheduling-settings'
import { Route as AuthenticatedSectionsRouteImport } from './routes/_authenticated/sections'
import { Route as AuthenticatedSessionTypesRouteImport } from './routes/_authenticated/session-types'
import { Route as AuthenticatedSharedCoursesRouteImport } from './routes/_authenticated/shared-courses'
import { Route as AuthenticatedStudyPlansRouteImport } from './routes/_authenticated/study-plans'
import { Route as AuthenticatedTeachingAssignmentsRouteImport } from './routes/_authenticated/teaching-assignments'
import { Route as AuthenticatedTermsRouteImport } from './routes/_authenticated/terms'
import { Route as AuthenticatedTimeSlotTemplatesRouteImport } from './routes/_authenticated/time-slot-templates'
import { Route as AuthenticatedTimeSlotsRouteImport } from './routes/_authenticated/time-slots'
import { Route as AuthenticatedUniversitiesRouteImport } from './routes/_authenticated/universities'
import { Route as AuthenticatedUnresolvedSuggestionsRouteImport } from './routes/_authenticated/unresolved-suggestions'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports.index'
import { Route as AuthenticatedReportsAcademicAffairsRouteImport } from './routes/_authenticated/reports.academic-affairs'
import { Route as AuthenticatedReportsConflictsRouteImport } from './routes/_authenticated/reports.conflicts'
import { Route as AuthenticatedReportsCurrentTimetableRouteImport } from './routes/_authenticated/reports.current-timetable'
import { Route as AuthenticatedReportsDataReadinessRouteImport } from './routes/_authenticated/reports.data-readiness'
import { Route as AuthenticatedReportsDepartmentScheduleRouteImport } from './routes/_authenticated/reports.department-schedule'
import { Route as AuthenticatedReportsEducationSourceTimetableRouteImport } from './routes/_authenticated/reports.education-source-timetable'
import { Route as AuthenticatedReportsInstructorScheduleRouteImport } from './routes/_authenticated/reports.instructor-schedule'
import { Route as AuthenticatedReportsInstructorWorkloadRouteImport } from './routes/_authenticated/reports.instructor-workload'
import { Route as AuthenticatedReportsInstructorsRouteImport } from './routes/_authenticated/reports.instructors'
import { Route as AuthenticatedReportsLeadershipRouteImport } from './routes/_authenticated/reports.leadership'
import { Route as AuthenticatedReportsProgramLevelTimetableRouteImport } from './routes/_authenticated/reports.program-level-timetable'
import { Route as AuthenticatedReportsPublishedTimetableRouteImport } from './routes/_authenticated/reports.published-timetable'
import { Route as AuthenticatedReportsQualityAnalyticsRouteImport } from './routes/_authenticated/reports.quality-analytics'
import { Route as AuthenticatedReportsQualitySummaryRouteImport } from './routes/_authenticated/reports.quality-summary'
import { Route as AuthenticatedReportsRoomTimetableRouteImport } from './routes/_authenticated/reports.room-timetable'
import { Route as AuthenticatedReportsRoomUtilizationRouteImport } from './routes/_authenticated/reports.room-utilization'
import { Route as AuthenticatedReportsRoomsReportRouteImport } from './routes/_authenticated/reports.rooms-report'
import { Route as AuthenticatedReportsSectionTimetableRouteImport } from './routes/_authenticated/reports.section-timetable'
import { Route as AuthenticatedReportsTeachingDemandCapacityRouteImport } from './routes/_authenticated/reports.teaching-demand-capacity'
import { Route as AuthenticatedReportsUniversityOverviewRouteImport } from './routes/_authenticated/reports.university-overview'
import { Route as AuthenticatedReportsUnscheduledRouteImport } from './routes/_authenticated/reports.unscheduled'
import { Route as AuthenticatedTimetableVersionIdRouteImport } from './routes/_authenticated/timetable.$versionId'
import { Route as AuthenticatedTimetableVersionIdPrintRouteImport } from './routes/_authenticated/timetable_.$versionId.print'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyReportRoute = VerifyReportRouteImport.update({
  id: '/verify-report',
  path: '/verify-report',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAcademicCalendarRoute =
  AuthenticatedAcademicCalendarRouteImport.update({
    id: '/academic-calendar',
    path: '/academic-calendar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcademicCohortsRoute =
  AuthenticatedAcademicCohortsRouteImport.update({
    id: '/academic-cohorts',
    path: '/academic-cohorts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountSecurityRoute =
  AuthenticatedAccountSecurityRouteImport.update({
    id: '/account-security',
    path: '/account-security',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminToolsRoute = AuthenticatedAdminToolsRouteImport.update({
  id: '/admin-tools',
  path: '/admin-tools',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutoScheduleRoute =
  AuthenticatedAutoScheduleRouteImport.update({
    id: '/auto-schedule',
    path: '/auto-schedule',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAvailabilityRoute =
  AuthenticatedAvailabilityRouteImport.update({
    id: '/availability',
    path: '/availability',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBuildingsRoute = AuthenticatedBuildingsRouteImport.update({
  id: '/buildings',
  path: '/buildings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCollegesRoute = AuthenticatedCollegesRouteImport.update({
  id: '/colleges',
  path: '/colleges',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConflictChecksRoute =
  AuthenticatedConflictChecksRouteImport.update({
    id: '/conflict-checks',
    path: '/conflict-checks',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConstraintSettingsRoute =
  AuthenticatedConstraintSettingsRouteImport.update({
    id: '/constraint-settings',
    path: '/constraint-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCourseOfferingsRoute =
  AuthenticatedCourseOfferingsRouteImport.update({
    id: '/course-offerings',
    path: '/course-offerings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoursesRoute = AuthenticatedCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDailyBreaksRoute =
  AuthenticatedDailyBreaksRouteImport.update({
    id: '/daily-breaks',
    path: '/daily-breaks',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDataCleanupRoute =
  AuthenticatedDataCleanupRouteImport.update({
    id: '/data-cleanup',
    path: '/data-cleanup',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDataOnboardingRoute =
  AuthenticatedDataOnboardingRouteImport.update({
    id: '/data-onboarding',
    path: '/data-onboarding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDataReadinessRoute =
  AuthenticatedDataReadinessRouteImport.update({
    id: '/data-readiness',
    path: '/data-readiness',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDataTemplatesRoute =
  AuthenticatedDataTemplatesRouteImport.update({
    id: '/data-templates',
    path: '/data-templates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDeliveryGroupsRoute =
  AuthenticatedDeliveryGroupsRouteImport.update({
    id: '/delivery-groups',
    path: '/delivery-groups',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDepartmentsRoute =
  AuthenticatedDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportHistoryRoute =
  AuthenticatedImportHistoryRouteImport.update({
    id: '/import-history',
    path: '/import-history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImportTemplatesRoute =
  AuthenticatedImportTemplatesRouteImport.update({
    id: '/import-templates',
    path: '/import-templates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstructorTypesRoute =
  AuthenticatedInstructorTypesRouteImport.update({
    id: '/instructor-types',
    path: '/instructor-types',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstructorsRoute =
  AuthenticatedInstructorsRouteImport.update({
    id: '/instructors',
    path: '/instructors',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedItcsCutoverRoute =
  AuthenticatedItcsCutoverRouteImport.update({
    id: '/itcs-cutover',
    path: '/itcs-cutover',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedItcsReviewProposalRoute =
  AuthenticatedItcsReviewProposalRouteImport.update({
    id: '/itcs-review-proposal',
    path: '/itcs-review-proposal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyCollegeRoute = AuthenticatedMyCollegeRouteImport.update({
  id: '/my-college',
  path: '/my-college',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgramsRoute = AuthenticatedProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPublishedSchedulesRoute =
  AuthenticatedPublishedSchedulesRouteImport.update({
    id: '/published-schedules',
    path: '/published-schedules',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoomTypesRoute = AuthenticatedRoomTypesRouteImport.update({
  id: '/room-types',
  path: '/room-types',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoomsRoute = AuthenticatedRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScheduleBuilderRoute =
  AuthenticatedScheduleBuilderRouteImport.update({
    id: '/schedule-builder',
    path: '/schedule-builder',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedScheduleQualityRoute =
  AuthenticatedScheduleQualityRouteImport.update({
    id: '/schedule-quality',
    path: '/schedule-quality',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedScheduleVersionsRoute =
  AuthenticatedScheduleVersionsRouteImport.update({
    id: '/schedule-versions',
    path: '/schedule-versions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSchedulingHeadcountsRoute =
  AuthenticatedSchedulingHeadcountsRouteImport.update({
    id: '/scheduling-headcounts',
    path: '/scheduling-headcounts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSchedulingSettingsRoute =
  AuthenticatedSchedulingSettingsRouteImport.update({
    id: '/scheduling-settings',
    path: '/scheduling-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSectionsRoute = AuthenticatedSectionsRouteImport.update({
  id: '/sections',
  path: '/sections',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSessionTypesRoute =
  AuthenticatedSessionTypesRouteImport.update({
    id: '/session-types',
    path: '/session-types',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSharedCoursesRoute =
  AuthenticatedSharedCoursesRouteImport.update({
    id: '/shared-courses',
    path: '/shared-courses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudyPlansRoute = AuthenticatedStudyPlansRouteImport.update({
  id: '/study-plans',
  path: '/study-plans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeachingAssignmentsRoute =
  AuthenticatedTeachingAssignmentsRouteImport.update({
    id: '/teaching-assignments',
    path: '/teaching-assignments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTermsRoute = AuthenticatedTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTimeSlotTemplatesRoute =
  AuthenticatedTimeSlotTemplatesRouteImport.update({
    id: '/time-slot-templates',
    path: '/time-slot-templates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTimeSlotsRoute = AuthenticatedTimeSlotsRouteImport.update({
  id: '/time-slots',
  path: '/time-slots',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUniversitiesRoute =
  AuthenticatedUniversitiesRouteImport.update({
    id: '/universities',
    path: '/universities',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUnresolvedSuggestionsRoute =
  AuthenticatedUnresolvedSuggestionsRouteImport.update({
    id: '/unresolved-suggestions',
    path: '/unresolved-suggestions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsAcademicAffairsRoute =
  AuthenticatedReportsAcademicAffairsRouteImport.update({
    id: '/academic-affairs',
    path: '/academic-affairs',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsConflictsRoute =
  AuthenticatedReportsConflictsRouteImport.update({
    id: '/conflicts',
    path: '/conflicts',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsCurrentTimetableRoute =
  AuthenticatedReportsCurrentTimetableRouteImport.update({
    id: '/current-timetable',
    path: '/current-timetable',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsDataReadinessRoute =
  AuthenticatedReportsDataReadinessRouteImport.update({
    id: '/data-readiness',
    path: '/data-readiness',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsDepartmentScheduleRoute =
  AuthenticatedReportsDepartmentScheduleRouteImport.update({
    id: '/department-schedule',
    path: '/department-schedule',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsEducationSourceTimetableRoute =
  AuthenticatedReportsEducationSourceTimetableRouteImport.update({
    id: '/education-source-timetable',
    path: '/education-source-timetable',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsInstructorScheduleRoute =
  AuthenticatedReportsInstructorScheduleRouteImport.update({
    id: '/instructor-schedule',
    path: '/instructor-schedule',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsInstructorWorkloadRoute =
  AuthenticatedReportsInstructorWorkloadRouteImport.update({
    id: '/instructor-workload',
    path: '/instructor-workload',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsInstructorsRoute =
  AuthenticatedReportsInstructorsRouteImport.update({
    id: '/instructors',
    path: '/instructors',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsLeadershipRoute =
  AuthenticatedReportsLeadershipRouteImport.update({
    id: '/leadership',
    path: '/leadership',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsProgramLevelTimetableRoute =
  AuthenticatedReportsProgramLevelTimetableRouteImport.update({
    id: '/program-level-timetable',
    path: '/program-level-timetable',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsPublishedTimetableRoute =
  AuthenticatedReportsPublishedTimetableRouteImport.update({
    id: '/published-timetable',
    path: '/published-timetable',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsQualityAnalyticsRoute =
  AuthenticatedReportsQualityAnalyticsRouteImport.update({
    id: '/quality-analytics',
    path: '/quality-analytics',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsQualitySummaryRoute =
  AuthenticatedReportsQualitySummaryRouteImport.update({
    id: '/quality-summary',
    path: '/quality-summary',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsRoomTimetableRoute =
  AuthenticatedReportsRoomTimetableRouteImport.update({
    id: '/room-timetable',
    path: '/room-timetable',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsRoomUtilizationRoute =
  AuthenticatedReportsRoomUtilizationRouteImport.update({
    id: '/room-utilization',
    path: '/room-utilization',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsRoomsReportRoute =
  AuthenticatedReportsRoomsReportRouteImport.update({
    id: '/rooms-report',
    path: '/rooms-report',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsSectionTimetableRoute =
  AuthenticatedReportsSectionTimetableRouteImport.update({
    id: '/section-timetable',
    path: '/section-timetable',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsTeachingDemandCapacityRoute =
  AuthenticatedReportsTeachingDemandCapacityRouteImport.update({
    id: '/teaching-demand-capacity',
    path: '/teaching-demand-capacity',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsUniversityOverviewRoute =
  AuthenticatedReportsUniversityOverviewRouteImport.update({
    id: '/university-overview',
    path: '/university-overview',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsUnscheduledRoute =
  AuthenticatedReportsUnscheduledRouteImport.update({
    id: '/unscheduled',
    path: '/unscheduled',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedTimetableVersionIdRoute =
  AuthenticatedTimetableVersionIdRouteImport.update({
    id: '/timetable/$versionId',
    path: '/timetable/$versionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTimetableVersionIdPrintRoute =
  AuthenticatedTimetableVersionIdPrintRouteImport.update({
    id: '/timetable_/$versionId/print',
    path: '/timetable/$versionId/print',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-report': typeof VerifyReportRoute
  '/academic-calendar': typeof AuthenticatedAcademicCalendarRoute
  '/academic-cohorts': typeof AuthenticatedAcademicCohortsRoute
  '/account-security': typeof AuthenticatedAccountSecurityRoute
  '/admin-tools': typeof AuthenticatedAdminToolsRoute
  '/auto-schedule': typeof AuthenticatedAutoScheduleRoute
  '/availability': typeof AuthenticatedAvailabilityRoute
  '/buildings': typeof AuthenticatedBuildingsRoute
  '/colleges': typeof AuthenticatedCollegesRoute
  '/conflict-checks': typeof AuthenticatedConflictChecksRoute
  '/constraint-settings': typeof AuthenticatedConstraintSettingsRoute
  '/course-offerings': typeof AuthenticatedCourseOfferingsRoute
  '/courses': typeof AuthenticatedCoursesRoute
  '/daily-breaks': typeof AuthenticatedDailyBreaksRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/data-cleanup': typeof AuthenticatedDataCleanupRoute
  '/data-onboarding': typeof AuthenticatedDataOnboardingRoute
  '/data-readiness': typeof AuthenticatedDataReadinessRoute
  '/data-templates': typeof AuthenticatedDataTemplatesRoute
  '/delivery-groups': typeof AuthenticatedDeliveryGroupsRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/import': typeof AuthenticatedImportRoute
  '/import-history': typeof AuthenticatedImportHistoryRoute
  '/import-templates': typeof AuthenticatedImportTemplatesRoute
  '/instructor-types': typeof AuthenticatedInstructorTypesRoute
  '/instructors': typeof AuthenticatedInstructorsRoute
  '/itcs-cutover': typeof AuthenticatedItcsCutoverRoute
  '/itcs-review-proposal': typeof AuthenticatedItcsReviewProposalRoute
  '/my-college': typeof AuthenticatedMyCollegeRoute
  '/programs': typeof AuthenticatedProgramsRoute
  '/published-schedules': typeof AuthenticatedPublishedSchedulesRoute
  '/reports': typeof AuthenticatedReportsRouteWithChildren
  '/room-types': typeof AuthenticatedRoomTypesRoute
  '/rooms': typeof AuthenticatedRoomsRoute
  '/schedule-builder': typeof AuthenticatedScheduleBuilderRoute
  '/schedule-quality': typeof AuthenticatedScheduleQualityRoute
  '/schedule-versions': typeof AuthenticatedScheduleVersionsRoute
  '/scheduling-headcounts': typeof AuthenticatedSchedulingHeadcountsRoute
  '/scheduling-settings': typeof AuthenticatedSchedulingSettingsRoute
  '/sections': typeof AuthenticatedSectionsRoute
  '/session-types': typeof AuthenticatedSessionTypesRoute
  '/shared-courses': typeof AuthenticatedSharedCoursesRoute
  '/study-plans': typeof AuthenticatedStudyPlansRoute
  '/teaching-assignments': typeof AuthenticatedTeachingAssignmentsRoute
  '/terms': typeof AuthenticatedTermsRoute
  '/time-slot-templates': typeof AuthenticatedTimeSlotTemplatesRoute
  '/time-slots': typeof AuthenticatedTimeSlotsRoute
  '/universities': typeof AuthenticatedUniversitiesRoute
  '/unresolved-suggestions': typeof AuthenticatedUnresolvedSuggestionsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/reports/academic-affairs': typeof AuthenticatedReportsAcademicAffairsRoute
  '/reports/conflicts': typeof AuthenticatedReportsConflictsRoute
  '/reports/current-timetable': typeof AuthenticatedReportsCurrentTimetableRoute
  '/reports/data-readiness': typeof AuthenticatedReportsDataReadinessRoute
  '/reports/department-schedule': typeof AuthenticatedReportsDepartmentScheduleRoute
  '/reports/education-source-timetable': typeof AuthenticatedReportsEducationSourceTimetableRoute
  '/reports/instructor-schedule': typeof AuthenticatedReportsInstructorScheduleRoute
  '/reports/instructor-workload': typeof AuthenticatedReportsInstructorWorkloadRoute
  '/reports/instructors': typeof AuthenticatedReportsInstructorsRoute
  '/reports/leadership': typeof AuthenticatedReportsLeadershipRoute
  '/reports/program-level-timetable': typeof AuthenticatedReportsProgramLevelTimetableRoute
  '/reports/published-timetable': typeof AuthenticatedReportsPublishedTimetableRoute
  '/reports/quality-analytics': typeof AuthenticatedReportsQualityAnalyticsRoute
  '/reports/quality-summary': typeof AuthenticatedReportsQualitySummaryRoute
  '/reports/room-timetable': typeof AuthenticatedReportsRoomTimetableRoute
  '/reports/room-utilization': typeof AuthenticatedReportsRoomUtilizationRoute
  '/reports/rooms-report': typeof AuthenticatedReportsRoomsReportRoute
  '/reports/section-timetable': typeof AuthenticatedReportsSectionTimetableRoute
  '/reports/teaching-demand-capacity': typeof AuthenticatedReportsTeachingDemandCapacityRoute
  '/reports/university-overview': typeof AuthenticatedReportsUniversityOverviewRoute
  '/reports/unscheduled': typeof AuthenticatedReportsUnscheduledRoute
  '/timetable/$versionId': typeof AuthenticatedTimetableVersionIdRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/timetable/$versionId/print': typeof AuthenticatedTimetableVersionIdPrintRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-report': typeof VerifyReportRoute
  '/academic-calendar': typeof AuthenticatedAcademicCalendarRoute
  '/academic-cohorts': typeof AuthenticatedAcademicCohortsRoute
  '/account-security': typeof AuthenticatedAccountSecurityRoute
  '/admin-tools': typeof AuthenticatedAdminToolsRoute
  '/auto-schedule': typeof AuthenticatedAutoScheduleRoute
  '/availability': typeof AuthenticatedAvailabilityRoute
  '/buildings': typeof AuthenticatedBuildingsRoute
  '/colleges': typeof AuthenticatedCollegesRoute
  '/conflict-checks': typeof AuthenticatedConflictChecksRoute
  '/constraint-settings': typeof AuthenticatedConstraintSettingsRoute
  '/course-offerings': typeof AuthenticatedCourseOfferingsRoute
  '/courses': typeof AuthenticatedCoursesRoute
  '/daily-breaks': typeof AuthenticatedDailyBreaksRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/data-cleanup': typeof AuthenticatedDataCleanupRoute
  '/data-onboarding': typeof AuthenticatedDataOnboardingRoute
  '/data-readiness': typeof AuthenticatedDataReadinessRoute
  '/data-templates': typeof AuthenticatedDataTemplatesRoute
  '/delivery-groups': typeof AuthenticatedDeliveryGroupsRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/import': typeof AuthenticatedImportRoute
  '/import-history': typeof AuthenticatedImportHistoryRoute
  '/import-templates': typeof AuthenticatedImportTemplatesRoute
  '/instructor-types': typeof AuthenticatedInstructorTypesRoute
  '/instructors': typeof AuthenticatedInstructorsRoute
  '/itcs-cutover': typeof AuthenticatedItcsCutoverRoute
  '/itcs-review-proposal': typeof AuthenticatedItcsReviewProposalRoute
  '/my-college': typeof AuthenticatedMyCollegeRoute
  '/programs': typeof AuthenticatedProgramsRoute
  '/published-schedules': typeof AuthenticatedPublishedSchedulesRoute
  '/room-types': typeof AuthenticatedRoomTypesRoute
  '/rooms': typeof AuthenticatedRoomsRoute
  '/schedule-builder': typeof AuthenticatedScheduleBuilderRoute
  '/schedule-quality': typeof AuthenticatedScheduleQualityRoute
  '/schedule-versions': typeof AuthenticatedScheduleVersionsRoute
  '/scheduling-headcounts': typeof AuthenticatedSchedulingHeadcountsRoute
  '/scheduling-settings': typeof AuthenticatedSchedulingSettingsRoute
  '/sections': typeof AuthenticatedSectionsRoute
  '/session-types': typeof AuthenticatedSessionTypesRoute
  '/shared-courses': typeof AuthenticatedSharedCoursesRoute
  '/study-plans': typeof AuthenticatedStudyPlansRoute
  '/teaching-assignments': typeof AuthenticatedTeachingAssignmentsRoute
  '/terms': typeof AuthenticatedTermsRoute
  '/time-slot-templates': typeof AuthenticatedTimeSlotTemplatesRoute
  '/time-slots': typeof AuthenticatedTimeSlotsRoute
  '/universities': typeof AuthenticatedUniversitiesRoute
  '/unresolved-suggestions': typeof AuthenticatedUnresolvedSuggestionsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/reports/academic-affairs': typeof AuthenticatedReportsAcademicAffairsRoute
  '/reports/conflicts': typeof AuthenticatedReportsConflictsRoute
  '/reports/current-timetable': typeof AuthenticatedReportsCurrentTimetableRoute
  '/reports/data-readiness': typeof AuthenticatedReportsDataReadinessRoute
  '/reports/department-schedule': typeof AuthenticatedReportsDepartmentScheduleRoute
  '/reports/education-source-timetable': typeof AuthenticatedReportsEducationSourceTimetableRoute
  '/reports/instructor-schedule': typeof AuthenticatedReportsInstructorScheduleRoute
  '/reports/instructor-workload': typeof AuthenticatedReportsInstructorWorkloadRoute
  '/reports/instructors': typeof AuthenticatedReportsInstructorsRoute
  '/reports/leadership': typeof AuthenticatedReportsLeadershipRoute
  '/reports/program-level-timetable': typeof AuthenticatedReportsProgramLevelTimetableRoute
  '/reports/published-timetable': typeof AuthenticatedReportsPublishedTimetableRoute
  '/reports/quality-analytics': typeof AuthenticatedReportsQualityAnalyticsRoute
  '/reports/quality-summary': typeof AuthenticatedReportsQualitySummaryRoute
  '/reports/room-timetable': typeof AuthenticatedReportsRoomTimetableRoute
  '/reports/room-utilization': typeof AuthenticatedReportsRoomUtilizationRoute
  '/reports/rooms-report': typeof AuthenticatedReportsRoomsReportRoute
  '/reports/section-timetable': typeof AuthenticatedReportsSectionTimetableRoute
  '/reports/teaching-demand-capacity': typeof AuthenticatedReportsTeachingDemandCapacityRoute
  '/reports/university-overview': typeof AuthenticatedReportsUniversityOverviewRoute
  '/reports/unscheduled': typeof AuthenticatedReportsUnscheduledRoute
  '/timetable/$versionId': typeof AuthenticatedTimetableVersionIdRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/timetable/$versionId/print': typeof AuthenticatedTimetableVersionIdPrintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-report': typeof VerifyReportRoute
  '/_authenticated/academic-calendar': typeof AuthenticatedAcademicCalendarRoute
  '/_authenticated/academic-cohorts': typeof AuthenticatedAcademicCohortsRoute
  '/_authenticated/account-security': typeof AuthenticatedAccountSecurityRoute
  '/_authenticated/admin-tools': typeof AuthenticatedAdminToolsRoute
  '/_authenticated/auto-schedule': typeof AuthenticatedAutoScheduleRoute
  '/_authenticated/availability': typeof AuthenticatedAvailabilityRoute
  '/_authenticated/buildings': typeof AuthenticatedBuildingsRoute
  '/_authenticated/colleges': typeof AuthenticatedCollegesRoute
  '/_authenticated/conflict-checks': typeof AuthenticatedConflictChecksRoute
  '/_authenticated/constraint-settings': typeof AuthenticatedConstraintSettingsRoute
  '/_authenticated/course-offerings': typeof AuthenticatedCourseOfferingsRoute
  '/_authenticated/courses': typeof AuthenticatedCoursesRoute
  '/_authenticated/daily-breaks': typeof AuthenticatedDailyBreaksRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/data-cleanup': typeof AuthenticatedDataCleanupRoute
  '/_authenticated/data-onboarding': typeof AuthenticatedDataOnboardingRoute
  '/_authenticated/data-readiness': typeof AuthenticatedDataReadinessRoute
  '/_authenticated/data-templates': typeof AuthenticatedDataTemplatesRoute
  '/_authenticated/delivery-groups': typeof AuthenticatedDeliveryGroupsRoute
  '/_authenticated/departments': typeof AuthenticatedDepartmentsRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/import-history': typeof AuthenticatedImportHistoryRoute
  '/_authenticated/import-templates': typeof AuthenticatedImportTemplatesRoute
  '/_authenticated/instructor-types': typeof AuthenticatedInstructorTypesRoute
  '/_authenticated/instructors': typeof AuthenticatedInstructorsRoute
  '/_authenticated/itcs-cutover': typeof AuthenticatedItcsCutoverRoute
  '/_authenticated/itcs-review-proposal': typeof AuthenticatedItcsReviewProposalRoute
  '/_authenticated/my-college': typeof AuthenticatedMyCollegeRoute
  '/_authenticated/programs': typeof AuthenticatedProgramsRoute
  '/_authenticated/published-schedules': typeof AuthenticatedPublishedSchedulesRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRouteWithChildren
  '/_authenticated/room-types': typeof AuthenticatedRoomTypesRoute
  '/_authenticated/rooms': typeof AuthenticatedRoomsRoute
  '/_authenticated/schedule-builder': typeof AuthenticatedScheduleBuilderRoute
  '/_authenticated/schedule-quality': typeof AuthenticatedScheduleQualityRoute
  '/_authenticated/schedule-versions': typeof AuthenticatedScheduleVersionsRoute
  '/_authenticated/scheduling-headcounts': typeof AuthenticatedSchedulingHeadcountsRoute
  '/_authenticated/scheduling-settings': typeof AuthenticatedSchedulingSettingsRoute
  '/_authenticated/sections': typeof AuthenticatedSectionsRoute
  '/_authenticated/session-types': typeof AuthenticatedSessionTypesRoute
  '/_authenticated/shared-courses': typeof AuthenticatedSharedCoursesRoute
  '/_authenticated/study-plans': typeof AuthenticatedStudyPlansRoute
  '/_authenticated/teaching-assignments': typeof AuthenticatedTeachingAssignmentsRoute
  '/_authenticated/terms': typeof AuthenticatedTermsRoute
  '/_authenticated/time-slot-templates': typeof AuthenticatedTimeSlotTemplatesRoute
  '/_authenticated/time-slots': typeof AuthenticatedTimeSlotsRoute
  '/_authenticated/universities': typeof AuthenticatedUniversitiesRoute
  '/_authenticated/unresolved-suggestions': typeof AuthenticatedUnresolvedSuggestionsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/reports/academic-affairs': typeof AuthenticatedReportsAcademicAffairsRoute
  '/_authenticated/reports/conflicts': typeof AuthenticatedReportsConflictsRoute
  '/_authenticated/reports/current-timetable': typeof AuthenticatedReportsCurrentTimetableRoute
  '/_authenticated/reports/data-readiness': typeof AuthenticatedReportsDataReadinessRoute
  '/_authenticated/reports/department-schedule': typeof AuthenticatedReportsDepartmentScheduleRoute
  '/_authenticated/reports/education-source-timetable': typeof AuthenticatedReportsEducationSourceTimetableRoute
  '/_authenticated/reports/instructor-schedule': typeof AuthenticatedReportsInstructorScheduleRoute
  '/_authenticated/reports/instructor-workload': typeof AuthenticatedReportsInstructorWorkloadRoute
  '/_authenticated/reports/instructors': typeof AuthenticatedReportsInstructorsRoute
  '/_authenticated/reports/leadership': typeof AuthenticatedReportsLeadershipRoute
  '/_authenticated/reports/program-level-timetable': typeof AuthenticatedReportsProgramLevelTimetableRoute
  '/_authenticated/reports/published-timetable': typeof AuthenticatedReportsPublishedTimetableRoute
  '/_authenticated/reports/quality-analytics': typeof AuthenticatedReportsQualityAnalyticsRoute
  '/_authenticated/reports/quality-summary': typeof AuthenticatedReportsQualitySummaryRoute
  '/_authenticated/reports/room-timetable': typeof AuthenticatedReportsRoomTimetableRoute
  '/_authenticated/reports/room-utilization': typeof AuthenticatedReportsRoomUtilizationRoute
  '/_authenticated/reports/rooms-report': typeof AuthenticatedReportsRoomsReportRoute
  '/_authenticated/reports/section-timetable': typeof AuthenticatedReportsSectionTimetableRoute
  '/_authenticated/reports/teaching-demand-capacity': typeof AuthenticatedReportsTeachingDemandCapacityRoute
  '/_authenticated/reports/university-overview': typeof AuthenticatedReportsUniversityOverviewRoute
  '/_authenticated/reports/unscheduled': typeof AuthenticatedReportsUnscheduledRoute
  '/_authenticated/timetable/$versionId': typeof AuthenticatedTimetableVersionIdRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/timetable_/$versionId/print': typeof AuthenticatedTimetableVersionIdPrintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/verify-report'
    | '/academic-calendar'
    | '/academic-cohorts'
    | '/account-security'
    | '/admin-tools'
    | '/auto-schedule'
    | '/availability'
    | '/buildings'
    | '/colleges'
    | '/conflict-checks'
    | '/constraint-settings'
    | '/course-offerings'
    | '/courses'
    | '/daily-breaks'
    | '/dashboard'
    | '/data-cleanup'
    | '/data-onboarding'
    | '/data-readiness'
    | '/data-templates'
    | '/delivery-groups'
    | '/departments'
    | '/import'
    | '/import-history'
    | '/import-templates'
    | '/instructor-types'
    | '/instructors'
    | '/itcs-cutover'
    | '/itcs-review-proposal'
    | '/my-college'
    | '/programs'
    | '/published-schedules'
    | '/reports'
    | '/room-types'
    | '/rooms'
    | '/schedule-builder'
    | '/schedule-quality'
    | '/schedule-versions'
    | '/scheduling-headcounts'
    | '/scheduling-settings'
    | '/sections'
    | '/session-types'
    | '/shared-courses'
    | '/study-plans'
    | '/teaching-assignments'
    | '/terms'
    | '/time-slot-templates'
    | '/time-slots'
    | '/universities'
    | '/unresolved-suggestions'
    | '/users'
    | '/reports/academic-affairs'
    | '/reports/conflicts'
    | '/reports/current-timetable'
    | '/reports/data-readiness'
    | '/reports/department-schedule'
    | '/reports/education-source-timetable'
    | '/reports/instructor-schedule'
    | '/reports/instructor-workload'
    | '/reports/instructors'
    | '/reports/leadership'
    | '/reports/program-level-timetable'
    | '/reports/published-timetable'
    | '/reports/quality-analytics'
    | '/reports/quality-summary'
    | '/reports/room-timetable'
    | '/reports/room-utilization'
    | '/reports/rooms-report'
    | '/reports/section-timetable'
    | '/reports/teaching-demand-capacity'
    | '/reports/university-overview'
    | '/reports/unscheduled'
    | '/timetable/$versionId'
    | '/reports/'
    | '/timetable/$versionId/print'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/verify-report'
    | '/academic-calendar'
    | '/academic-cohorts'
    | '/account-security'
    | '/admin-tools'
    | '/auto-schedule'
    | '/availability'
    | '/buildings'
    | '/colleges'
    | '/conflict-checks'
    | '/constraint-settings'
    | '/course-offerings'
    | '/courses'
    | '/daily-breaks'
    | '/dashboard'
    | '/data-cleanup'
    | '/data-onboarding'
    | '/data-readiness'
    | '/data-templates'
    | '/delivery-groups'
    | '/departments'
    | '/import'
    | '/import-history'
    | '/import-templates'
    | '/instructor-types'
    | '/instructors'
    | '/itcs-cutover'
    | '/itcs-review-proposal'
    | '/my-college'
    | '/programs'
    | '/published-schedules'
    | '/room-types'
    | '/rooms'
    | '/schedule-builder'
    | '/schedule-quality'
    | '/schedule-versions'
    | '/scheduling-headcounts'
    | '/scheduling-settings'
    | '/sections'
    | '/session-types'
    | '/shared-courses'
    | '/study-plans'
    | '/teaching-assignments'
    | '/terms'
    | '/time-slot-templates'
    | '/time-slots'
    | '/universities'
    | '/unresolved-suggestions'
    | '/users'
    | '/reports/academic-affairs'
    | '/reports/conflicts'
    | '/reports/current-timetable'
    | '/reports/data-readiness'
    | '/reports/department-schedule'
    | '/reports/education-source-timetable'
    | '/reports/instructor-schedule'
    | '/reports/instructor-workload'
    | '/reports/instructors'
    | '/reports/leadership'
    | '/reports/program-level-timetable'
    | '/reports/published-timetable'
    | '/reports/quality-analytics'
    | '/reports/quality-summary'
    | '/reports/room-timetable'
    | '/reports/room-utilization'
    | '/reports/rooms-report'
    | '/reports/section-timetable'
    | '/reports/teaching-demand-capacity'
    | '/reports/university-overview'
    | '/reports/unscheduled'
    | '/timetable/$versionId'
    | '/reports'
    | '/timetable/$versionId/print'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/verify-report'
    | '/_authenticated/academic-calendar'
    | '/_authenticated/academic-cohorts'
    | '/_authenticated/account-security'
    | '/_authenticated/admin-tools'
    | '/_authenticated/auto-schedule'
    | '/_authenticated/availability'
    | '/_authenticated/buildings'
    | '/_authenticated/colleges'
    | '/_authenticated/conflict-checks'
    | '/_authenticated/constraint-settings'
    | '/_authenticated/course-offerings'
    | '/_authenticated/courses'
    | '/_authenticated/daily-breaks'
    | '/_authenticated/dashboard'
    | '/_authenticated/data-cleanup'
    | '/_authenticated/data-onboarding'
    | '/_authenticated/data-readiness'
    | '/_authenticated/data-templates'
    | '/_authenticated/delivery-groups'
    | '/_authenticated/departments'
    | '/_authenticated/import'
    | '/_authenticated/import-history'
    | '/_authenticated/import-templates'
    | '/_authenticated/instructor-types'
    | '/_authenticated/instructors'
    | '/_authenticated/itcs-cutover'
    | '/_authenticated/itcs-review-proposal'
    | '/_authenticated/my-college'
    | '/_authenticated/programs'
    | '/_authenticated/published-schedules'
    | '/_authenticated/reports'
    | '/_authenticated/room-types'
    | '/_authenticated/rooms'
    | '/_authenticated/schedule-builder'
    | '/_authenticated/schedule-quality'
    | '/_authenticated/schedule-versions'
    | '/_authenticated/scheduling-headcounts'
    | '/_authenticated/scheduling-settings'
    | '/_authenticated/sections'
    | '/_authenticated/session-types'
    | '/_authenticated/shared-courses'
    | '/_authenticated/study-plans'
    | '/_authenticated/teaching-assignments'
    | '/_authenticated/terms'
    | '/_authenticated/time-slot-templates'
    | '/_authenticated/time-slots'
    | '/_authenticated/universities'
    | '/_authenticated/unresolved-suggestions'
    | '/_authenticated/users'
    | '/_authenticated/reports/academic-affairs'
    | '/_authenticated/reports/conflicts'
    | '/_authenticated/reports/current-timetable'
    | '/_authenticated/reports/data-readiness'
    | '/_authenticated/reports/department-schedule'
    | '/_authenticated/reports/education-source-timetable'
    | '/_authenticated/reports/instructor-schedule'
    | '/_authenticated/reports/instructor-workload'
    | '/_authenticated/reports/instructors'
    | '/_authenticated/reports/leadership'
    | '/_authenticated/reports/program-level-timetable'
    | '/_authenticated/reports/published-timetable'
    | '/_authenticated/reports/quality-analytics'
    | '/_authenticated/reports/quality-summary'
    | '/_authenticated/reports/room-timetable'
    | '/_authenticated/reports/room-utilization'
    | '/_authenticated/reports/rooms-report'
    | '/_authenticated/reports/section-timetable'
    | '/_authenticated/reports/teaching-demand-capacity'
    | '/_authenticated/reports/university-overview'
    | '/_authenticated/reports/unscheduled'
    | '/_authenticated/timetable/$versionId'
    | '/_authenticated/reports/'
    | '/_authenticated/timetable_/$versionId/print'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyReportRoute: typeof VerifyReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-report': {
      id: '/verify-report'
      path: '/verify-report'
      fullPath: '/verify-report'
      preLoaderRoute: typeof VerifyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/academic-calendar': {
      id: '/_authenticated/academic-calendar'
      path: '/academic-calendar'
      fullPath: '/academic-calendar'
      preLoaderRoute: typeof AuthenticatedAcademicCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academic-cohorts': {
      id: '/_authenticated/academic-cohorts'
      path: '/academic-cohorts'
      fullPath: '/academic-cohorts'
      preLoaderRoute: typeof AuthenticatedAcademicCohortsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account-security': {
      id: '/_authenticated/account-security'
      path: '/account-security'
      fullPath: '/account-security'
      preLoaderRoute: typeof AuthenticatedAccountSecurityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-tools': {
      id: '/_authenticated/admin-tools'
      path: '/admin-tools'
      fullPath: '/admin-tools'
      preLoaderRoute: typeof AuthenticatedAdminToolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auto-schedule': {
      id: '/_authenticated/auto-schedule'
      path: '/auto-schedule'
      fullPath: '/auto-schedule'
      preLoaderRoute: typeof AuthenticatedAutoScheduleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/availability': {
      id: '/_authenticated/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AuthenticatedAvailabilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buildings': {
      id: '/_authenticated/buildings'
      path: '/buildings'
      fullPath: '/buildings'
      preLoaderRoute: typeof AuthenticatedBuildingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/colleges': {
      id: '/_authenticated/colleges'
      path: '/colleges'
      fullPath: '/colleges'
      preLoaderRoute: typeof AuthenticatedCollegesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conflict-checks': {
      id: '/_authenticated/conflict-checks'
      path: '/conflict-checks'
      fullPath: '/conflict-checks'
      preLoaderRoute: typeof AuthenticatedConflictChecksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/constraint-settings': {
      id: '/_authenticated/constraint-settings'
      path: '/constraint-settings'
      fullPath: '/constraint-settings'
      preLoaderRoute: typeof AuthenticatedConstraintSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/course-offerings': {
      id: '/_authenticated/course-offerings'
      path: '/course-offerings'
      fullPath: '/course-offerings'
      preLoaderRoute: typeof AuthenticatedCourseOfferingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses': {
      id: '/_authenticated/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AuthenticatedCoursesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/daily-breaks': {
      id: '/_authenticated/daily-breaks'
      path: '/daily-breaks'
      fullPath: '/daily-breaks'
      preLoaderRoute: typeof AuthenticatedDailyBreaksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/data-cleanup': {
      id: '/_authenticated/data-cleanup'
      path: '/data-cleanup'
      fullPath: '/data-cleanup'
      preLoaderRoute: typeof AuthenticatedDataCleanupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/data-onboarding': {
      id: '/_authenticated/data-onboarding'
      path: '/data-onboarding'
      fullPath: '/data-onboarding'
      preLoaderRoute: typeof AuthenticatedDataOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/data-readiness': {
      id: '/_authenticated/data-readiness'
      path: '/data-readiness'
      fullPath: '/data-readiness'
      preLoaderRoute: typeof AuthenticatedDataReadinessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/data-templates': {
      id: '/_authenticated/data-templates'
      path: '/data-templates'
      fullPath: '/data-templates'
      preLoaderRoute: typeof AuthenticatedDataTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/delivery-groups': {
      id: '/_authenticated/delivery-groups'
      path: '/delivery-groups'
      fullPath: '/delivery-groups'
      preLoaderRoute: typeof AuthenticatedDeliveryGroupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/departments': {
      id: '/_authenticated/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AuthenticatedDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import-history': {
      id: '/_authenticated/import-history'
      path: '/import-history'
      fullPath: '/import-history'
      preLoaderRoute: typeof AuthenticatedImportHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import-templates': {
      id: '/_authenticated/import-templates'
      path: '/import-templates'
      fullPath: '/import-templates'
      preLoaderRoute: typeof AuthenticatedImportTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/instructor-types': {
      id: '/_authenticated/instructor-types'
      path: '/instructor-types'
      fullPath: '/instructor-types'
      preLoaderRoute: typeof AuthenticatedInstructorTypesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/instructors': {
      id: '/_authenticated/instructors'
      path: '/instructors'
      fullPath: '/instructors'
      preLoaderRoute: typeof AuthenticatedInstructorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/itcs-cutover': {
      id: '/_authenticated/itcs-cutover'
      path: '/itcs-cutover'
      fullPath: '/itcs-cutover'
      preLoaderRoute: typeof AuthenticatedItcsCutoverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/itcs-review-proposal': {
      id: '/_authenticated/itcs-review-proposal'
      path: '/itcs-review-proposal'
      fullPath: '/itcs-review-proposal'
      preLoaderRoute: typeof AuthenticatedItcsReviewProposalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-college': {
      id: '/_authenticated/my-college'
      path: '/my-college'
      fullPath: '/my-college'
      preLoaderRoute: typeof AuthenticatedMyCollegeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/programs': {
      id: '/_authenticated/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof AuthenticatedProgramsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/published-schedules': {
      id: '/_authenticated/published-schedules'
      path: '/published-schedules'
      fullPath: '/published-schedules'
      preLoaderRoute: typeof AuthenticatedPublishedSchedulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/room-types': {
      id: '/_authenticated/room-types'
      path: '/room-types'
      fullPath: '/room-types'
      preLoaderRoute: typeof AuthenticatedRoomTypesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rooms': {
      id: '/_authenticated/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AuthenticatedRoomsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedule-builder': {
      id: '/_authenticated/schedule-builder'
      path: '/schedule-builder'
      fullPath: '/schedule-builder'
      preLoaderRoute: typeof AuthenticatedScheduleBuilderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedule-quality': {
      id: '/_authenticated/schedule-quality'
      path: '/schedule-quality'
      fullPath: '/schedule-quality'
      preLoaderRoute: typeof AuthenticatedScheduleQualityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedule-versions': {
      id: '/_authenticated/schedule-versions'
      path: '/schedule-versions'
      fullPath: '/schedule-versions'
      preLoaderRoute: typeof AuthenticatedScheduleVersionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scheduling-headcounts': {
      id: '/_authenticated/scheduling-headcounts'
      path: '/scheduling-headcounts'
      fullPath: '/scheduling-headcounts'
      preLoaderRoute: typeof AuthenticatedSchedulingHeadcountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scheduling-settings': {
      id: '/_authenticated/scheduling-settings'
      path: '/scheduling-settings'
      fullPath: '/scheduling-settings'
      preLoaderRoute: typeof AuthenticatedSchedulingSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sections': {
      id: '/_authenticated/sections'
      path: '/sections'
      fullPath: '/sections'
      preLoaderRoute: typeof AuthenticatedSectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/session-types': {
      id: '/_authenticated/session-types'
      path: '/session-types'
      fullPath: '/session-types'
      preLoaderRoute: typeof AuthenticatedSessionTypesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shared-courses': {
      id: '/_authenticated/shared-courses'
      path: '/shared-courses'
      fullPath: '/shared-courses'
      preLoaderRoute: typeof AuthenticatedSharedCoursesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/study-plans': {
      id: '/_authenticated/study-plans'
      path: '/study-plans'
      fullPath: '/study-plans'
      preLoaderRoute: typeof AuthenticatedStudyPlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teaching-assignments': {
      id: '/_authenticated/teaching-assignments'
      path: '/teaching-assignments'
      fullPath: '/teaching-assignments'
      preLoaderRoute: typeof AuthenticatedTeachingAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/terms': {
      id: '/_authenticated/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof AuthenticatedTermsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/time-slot-templates': {
      id: '/_authenticated/time-slot-templates'
      path: '/time-slot-templates'
      fullPath: '/time-slot-templates'
      preLoaderRoute: typeof AuthenticatedTimeSlotTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/time-slots': {
      id: '/_authenticated/time-slots'
      path: '/time-slots'
      fullPath: '/time-slots'
      preLoaderRoute: typeof AuthenticatedTimeSlotsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/universities': {
      id: '/_authenticated/universities'
      path: '/universities'
      fullPath: '/universities'
      preLoaderRoute: typeof AuthenticatedUniversitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/unresolved-suggestions': {
      id: '/_authenticated/unresolved-suggestions'
      path: '/unresolved-suggestions'
      fullPath: '/unresolved-suggestions'
      preLoaderRoute: typeof AuthenticatedUnresolvedSuggestionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/academic-affairs': {
      id: '/_authenticated/reports/academic-affairs'
      path: '/academic-affairs'
      fullPath: '/reports/academic-affairs'
      preLoaderRoute: typeof AuthenticatedReportsAcademicAffairsRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/conflicts': {
      id: '/_authenticated/reports/conflicts'
      path: '/conflicts'
      fullPath: '/reports/conflicts'
      preLoaderRoute: typeof AuthenticatedReportsConflictsRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/current-timetable': {
      id: '/_authenticated/reports/current-timetable'
      path: '/current-timetable'
      fullPath: '/reports/current-timetable'
      preLoaderRoute: typeof AuthenticatedReportsCurrentTimetableRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/data-readiness': {
      id: '/_authenticated/reports/data-readiness'
      path: '/data-readiness'
      fullPath: '/reports/data-readiness'
      preLoaderRoute: typeof AuthenticatedReportsDataReadinessRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/department-schedule': {
      id: '/_authenticated/reports/department-schedule'
      path: '/department-schedule'
      fullPath: '/reports/department-schedule'
      preLoaderRoute: typeof AuthenticatedReportsDepartmentScheduleRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/education-source-timetable': {
      id: '/_authenticated/reports/education-source-timetable'
      path: '/education-source-timetable'
      fullPath: '/reports/education-source-timetable'
      preLoaderRoute: typeof AuthenticatedReportsEducationSourceTimetableRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/instructor-schedule': {
      id: '/_authenticated/reports/instructor-schedule'
      path: '/instructor-schedule'
      fullPath: '/reports/instructor-schedule'
      preLoaderRoute: typeof AuthenticatedReportsInstructorScheduleRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/instructor-workload': {
      id: '/_authenticated/reports/instructor-workload'
      path: '/instructor-workload'
      fullPath: '/reports/instructor-workload'
      preLoaderRoute: typeof AuthenticatedReportsInstructorWorkloadRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/instructors': {
      id: '/_authenticated/reports/instructors'
      path: '/instructors'
      fullPath: '/reports/instructors'
      preLoaderRoute: typeof AuthenticatedReportsInstructorsRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/leadership': {
      id: '/_authenticated/reports/leadership'
      path: '/leadership'
      fullPath: '/reports/leadership'
      preLoaderRoute: typeof AuthenticatedReportsLeadershipRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/program-level-timetable': {
      id: '/_authenticated/reports/program-level-timetable'
      path: '/program-level-timetable'
      fullPath: '/reports/program-level-timetable'
      preLoaderRoute: typeof AuthenticatedReportsProgramLevelTimetableRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/published-timetable': {
      id: '/_authenticated/reports/published-timetable'
      path: '/published-timetable'
      fullPath: '/reports/published-timetable'
      preLoaderRoute: typeof AuthenticatedReportsPublishedTimetableRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/quality-analytics': {
      id: '/_authenticated/reports/quality-analytics'
      path: '/quality-analytics'
      fullPath: '/reports/quality-analytics'
      preLoaderRoute: typeof AuthenticatedReportsQualityAnalyticsRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/quality-summary': {
      id: '/_authenticated/reports/quality-summary'
      path: '/quality-summary'
      fullPath: '/reports/quality-summary'
      preLoaderRoute: typeof AuthenticatedReportsQualitySummaryRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/room-timetable': {
      id: '/_authenticated/reports/room-timetable'
      path: '/room-timetable'
      fullPath: '/reports/room-timetable'
      preLoaderRoute: typeof AuthenticatedReportsRoomTimetableRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/room-utilization': {
      id: '/_authenticated/reports/room-utilization'
      path: '/room-utilization'
      fullPath: '/reports/room-utilization'
      preLoaderRoute: typeof AuthenticatedReportsRoomUtilizationRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/rooms-report': {
      id: '/_authenticated/reports/rooms-report'
      path: '/rooms-report'
      fullPath: '/reports/rooms-report'
      preLoaderRoute: typeof AuthenticatedReportsRoomsReportRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/section-timetable': {
      id: '/_authenticated/reports/section-timetable'
      path: '/section-timetable'
      fullPath: '/reports/section-timetable'
      preLoaderRoute: typeof AuthenticatedReportsSectionTimetableRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/teaching-demand-capacity': {
      id: '/_authenticated/reports/teaching-demand-capacity'
      path: '/teaching-demand-capacity'
      fullPath: '/reports/teaching-demand-capacity'
      preLoaderRoute: typeof AuthenticatedReportsTeachingDemandCapacityRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/university-overview': {
      id: '/_authenticated/reports/university-overview'
      path: '/university-overview'
      fullPath: '/reports/university-overview'
      preLoaderRoute: typeof AuthenticatedReportsUniversityOverviewRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/unscheduled': {
      id: '/_authenticated/reports/unscheduled'
      path: '/unscheduled'
      fullPath: '/reports/unscheduled'
      preLoaderRoute: typeof AuthenticatedReportsUnscheduledRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/timetable/$versionId': {
      id: '/_authenticated/timetable/$versionId'
      path: '/timetable/$versionId'
      fullPath: '/timetable/$versionId'
      preLoaderRoute: typeof AuthenticatedTimetableVersionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timetable_/$versionId/print': {
      id: '/_authenticated/timetable_/$versionId/print'
      path: '/timetable/$versionId/print'
      fullPath: '/timetable/$versionId/print'
      preLoaderRoute: typeof AuthenticatedTimetableVersionIdPrintRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedReportsRouteChildren {
  AuthenticatedReportsAcademicAffairsRoute: typeof AuthenticatedReportsAcademicAffairsRoute
  AuthenticatedReportsConflictsRoute: typeof AuthenticatedReportsConflictsRoute
  AuthenticatedReportsCurrentTimetableRoute: typeof AuthenticatedReportsCurrentTimetableRoute
  AuthenticatedReportsDataReadinessRoute: typeof AuthenticatedReportsDataReadinessRoute
  AuthenticatedReportsDepartmentScheduleRoute: typeof AuthenticatedReportsDepartmentScheduleRoute
  AuthenticatedReportsEducationSourceTimetableRoute: typeof AuthenticatedReportsEducationSourceTimetableRoute
  AuthenticatedReportsInstructorScheduleRoute: typeof AuthenticatedReportsInstructorScheduleRoute
  AuthenticatedReportsInstructorWorkloadRoute: typeof AuthenticatedReportsInstructorWorkloadRoute
  AuthenticatedReportsInstructorsRoute: typeof AuthenticatedReportsInstructorsRoute
  AuthenticatedReportsLeadershipRoute: typeof AuthenticatedReportsLeadershipRoute
  AuthenticatedReportsProgramLevelTimetableRoute: typeof AuthenticatedReportsProgramLevelTimetableRoute
  AuthenticatedReportsPublishedTimetableRoute: typeof AuthenticatedReportsPublishedTimetableRoute
  AuthenticatedReportsQualityAnalyticsRoute: typeof AuthenticatedReportsQualityAnalyticsRoute
  AuthenticatedReportsQualitySummaryRoute: typeof AuthenticatedReportsQualitySummaryRoute
  AuthenticatedReportsRoomTimetableRoute: typeof AuthenticatedReportsRoomTimetableRoute
  AuthenticatedReportsRoomUtilizationRoute: typeof AuthenticatedReportsRoomUtilizationRoute
  AuthenticatedReportsRoomsReportRoute: typeof AuthenticatedReportsRoomsReportRoute
  AuthenticatedReportsSectionTimetableRoute: typeof AuthenticatedReportsSectionTimetableRoute
  AuthenticatedReportsTeachingDemandCapacityRoute: typeof AuthenticatedReportsTeachingDemandCapacityRoute
  AuthenticatedReportsUniversityOverviewRoute: typeof AuthenticatedReportsUniversityOverviewRoute
  AuthenticatedReportsUnscheduledRoute: typeof AuthenticatedReportsUnscheduledRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
}

const AuthenticatedReportsRouteChildren: AuthenticatedReportsRouteChildren = {
  AuthenticatedReportsAcademicAffairsRoute:
    AuthenticatedReportsAcademicAffairsRoute,
  AuthenticatedReportsConflictsRoute: AuthenticatedReportsConflictsRoute,
  AuthenticatedReportsCurrentTimetableRoute:
    AuthenticatedReportsCurrentTimetableRoute,
  AuthenticatedReportsDataReadinessRoute:
    AuthenticatedReportsDataReadinessRoute,
  AuthenticatedReportsDepartmentScheduleRoute:
    AuthenticatedReportsDepartmentScheduleRoute,
  AuthenticatedReportsEducationSourceTimetableRoute:
    AuthenticatedReportsEducationSourceTimetableRoute,
  AuthenticatedReportsInstructorScheduleRoute:
    AuthenticatedReportsInstructorScheduleRoute,
  AuthenticatedReportsInstructorWorkloadRoute:
    AuthenticatedReportsInstructorWorkloadRoute,
  AuthenticatedReportsInstructorsRoute: AuthenticatedReportsInstructorsRoute,
  AuthenticatedReportsLeadershipRoute: AuthenticatedReportsLeadershipRoute,
  AuthenticatedReportsProgramLevelTimetableRoute:
    AuthenticatedReportsProgramLevelTimetableRoute,
  AuthenticatedReportsPublishedTimetableRoute:
    AuthenticatedReportsPublishedTimetableRoute,
  AuthenticatedReportsQualityAnalyticsRoute:
    AuthenticatedReportsQualityAnalyticsRoute,
  AuthenticatedReportsQualitySummaryRoute:
    AuthenticatedReportsQualitySummaryRoute,
  AuthenticatedReportsRoomTimetableRoute:
    AuthenticatedReportsRoomTimetableRoute,
  AuthenticatedReportsRoomUtilizationRoute:
    AuthenticatedReportsRoomUtilizationRoute,
  AuthenticatedReportsRoomsReportRoute: AuthenticatedReportsRoomsReportRoute,
  AuthenticatedReportsSectionTimetableRoute:
    AuthenticatedReportsSectionTimetableRoute,
  AuthenticatedReportsTeachingDemandCapacityRoute:
    AuthenticatedReportsTeachingDemandCapacityRoute,
  AuthenticatedReportsUniversityOverviewRoute:
    AuthenticatedReportsUniversityOverviewRoute,
  AuthenticatedReportsUnscheduledRoute: AuthenticatedReportsUnscheduledRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
}

const AuthenticatedReportsRouteWithChildren =
  AuthenticatedReportsRoute._addFileChildren(AuthenticatedReportsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAcademicCalendarRoute: typeof AuthenticatedAcademicCalendarRoute
  AuthenticatedAcademicCohortsRoute: typeof AuthenticatedAcademicCohortsRoute
  AuthenticatedAccountSecurityRoute: typeof AuthenticatedAccountSecurityRoute
  AuthenticatedAdminToolsRoute: typeof AuthenticatedAdminToolsRoute
  AuthenticatedAutoScheduleRoute: typeof AuthenticatedAutoScheduleRoute
  AuthenticatedAvailabilityRoute: typeof AuthenticatedAvailabilityRoute
  AuthenticatedBuildingsRoute: typeof AuthenticatedBuildingsRoute
  AuthenticatedCollegesRoute: typeof AuthenticatedCollegesRoute
  AuthenticatedConflictChecksRoute: typeof AuthenticatedConflictChecksRoute
  AuthenticatedConstraintSettingsRoute: typeof AuthenticatedConstraintSettingsRoute
  AuthenticatedCourseOfferingsRoute: typeof AuthenticatedCourseOfferingsRoute
  AuthenticatedCoursesRoute: typeof AuthenticatedCoursesRoute
  AuthenticatedDailyBreaksRoute: typeof AuthenticatedDailyBreaksRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDataCleanupRoute: typeof AuthenticatedDataCleanupRoute
  AuthenticatedDataOnboardingRoute: typeof AuthenticatedDataOnboardingRoute
  AuthenticatedDataReadinessRoute: typeof AuthenticatedDataReadinessRoute
  AuthenticatedDataTemplatesRoute: typeof AuthenticatedDataTemplatesRoute
  AuthenticatedDeliveryGroupsRoute: typeof AuthenticatedDeliveryGroupsRoute
  AuthenticatedDepartmentsRoute: typeof AuthenticatedDepartmentsRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedImportHistoryRoute: typeof AuthenticatedImportHistoryRoute
  AuthenticatedImportTemplatesRoute: typeof AuthenticatedImportTemplatesRoute
  AuthenticatedInstructorTypesRoute: typeof AuthenticatedInstructorTypesRoute
  AuthenticatedInstructorsRoute: typeof AuthenticatedInstructorsRoute
  AuthenticatedItcsCutoverRoute: typeof AuthenticatedItcsCutoverRoute
  AuthenticatedItcsReviewProposalRoute: typeof AuthenticatedItcsReviewProposalRoute
  AuthenticatedMyCollegeRoute: typeof AuthenticatedMyCollegeRoute
  AuthenticatedProgramsRoute: typeof AuthenticatedProgramsRoute
  AuthenticatedPublishedSchedulesRoute: typeof AuthenticatedPublishedSchedulesRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRouteWithChildren
  AuthenticatedRoomTypesRoute: typeof AuthenticatedRoomTypesRoute
  AuthenticatedRoomsRoute: typeof AuthenticatedRoomsRoute
  AuthenticatedScheduleBuilderRoute: typeof AuthenticatedScheduleBuilderRoute
  AuthenticatedScheduleQualityRoute: typeof AuthenticatedScheduleQualityRoute
  AuthenticatedScheduleVersionsRoute: typeof AuthenticatedScheduleVersionsRoute
  AuthenticatedSchedulingHeadcountsRoute: typeof AuthenticatedSchedulingHeadcountsRoute
  AuthenticatedSchedulingSettingsRoute: typeof AuthenticatedSchedulingSettingsRoute
  AuthenticatedSectionsRoute: typeof AuthenticatedSectionsRoute
  AuthenticatedSessionTypesRoute: typeof AuthenticatedSessionTypesRoute
  AuthenticatedSharedCoursesRoute: typeof AuthenticatedSharedCoursesRoute
  AuthenticatedStudyPlansRoute: typeof AuthenticatedStudyPlansRoute
  AuthenticatedTeachingAssignmentsRoute: typeof AuthenticatedTeachingAssignmentsRoute
  AuthenticatedTermsRoute: typeof AuthenticatedTermsRoute
  AuthenticatedTimeSlotTemplatesRoute: typeof AuthenticatedTimeSlotTemplatesRoute
  AuthenticatedTimeSlotsRoute: typeof AuthenticatedTimeSlotsRoute
  AuthenticatedUniversitiesRoute: typeof AuthenticatedUniversitiesRoute
  AuthenticatedUnresolvedSuggestionsRoute: typeof AuthenticatedUnresolvedSuggestionsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedTimetableVersionIdRoute: typeof AuthenticatedTimetableVersionIdRoute
  AuthenticatedTimetableVersionIdPrintRoute: typeof AuthenticatedTimetableVersionIdPrintRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAcademicCalendarRoute: AuthenticatedAcademicCalendarRoute,
  AuthenticatedAcademicCohortsRoute: AuthenticatedAcademicCohortsRoute,
  AuthenticatedAccountSecurityRoute: AuthenticatedAccountSecurityRoute,
  AuthenticatedAdminToolsRoute: AuthenticatedAdminToolsRoute,
  AuthenticatedAutoScheduleRoute: AuthenticatedAutoScheduleRoute,
  AuthenticatedAvailabilityRoute: AuthenticatedAvailabilityRoute,
  AuthenticatedBuildingsRoute: AuthenticatedBuildingsRoute,
  AuthenticatedCollegesRoute: AuthenticatedCollegesRoute,
  AuthenticatedConflictChecksRoute: AuthenticatedConflictChecksRoute,
  AuthenticatedConstraintSettingsRoute: AuthenticatedConstraintSettingsRoute,
  AuthenticatedCourseOfferingsRoute: AuthenticatedCourseOfferingsRoute,
  AuthenticatedCoursesRoute: AuthenticatedCoursesRoute,
  AuthenticatedDailyBreaksRoute: AuthenticatedDailyBreaksRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDataCleanupRoute: AuthenticatedDataCleanupRoute,
  AuthenticatedDataOnboardingRoute: AuthenticatedDataOnboardingRoute,
  AuthenticatedDataReadinessRoute: AuthenticatedDataReadinessRoute,
  AuthenticatedDataTemplatesRoute: AuthenticatedDataTemplatesRoute,
  AuthenticatedDeliveryGroupsRoute: AuthenticatedDeliveryGroupsRoute,
  AuthenticatedDepartmentsRoute: AuthenticatedDepartmentsRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedImportHistoryRoute: AuthenticatedImportHistoryRoute,
  AuthenticatedImportTemplatesRoute: AuthenticatedImportTemplatesRoute,
  AuthenticatedInstructorTypesRoute: AuthenticatedInstructorTypesRoute,
  AuthenticatedInstructorsRoute: AuthenticatedInstructorsRoute,
  AuthenticatedItcsCutoverRoute: AuthenticatedItcsCutoverRoute,
  AuthenticatedItcsReviewProposalRoute: AuthenticatedItcsReviewProposalRoute,
  AuthenticatedMyCollegeRoute: AuthenticatedMyCollegeRoute,
  AuthenticatedProgramsRoute: AuthenticatedProgramsRoute,
  AuthenticatedPublishedSchedulesRoute: AuthenticatedPublishedSchedulesRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRouteWithChildren,
  AuthenticatedRoomTypesRoute: AuthenticatedRoomTypesRoute,
  AuthenticatedRoomsRoute: AuthenticatedRoomsRoute,
  AuthenticatedScheduleBuilderRoute: AuthenticatedScheduleBuilderRoute,
  AuthenticatedScheduleQualityRoute: AuthenticatedScheduleQualityRoute,
  AuthenticatedScheduleVersionsRoute: AuthenticatedScheduleVersionsRoute,
  AuthenticatedSchedulingHeadcountsRoute:
    AuthenticatedSchedulingHeadcountsRoute,
  AuthenticatedSchedulingSettingsRoute: AuthenticatedSchedulingSettingsRoute,
  AuthenticatedSectionsRoute: AuthenticatedSectionsRoute,
  AuthenticatedSessionTypesRoute: AuthenticatedSessionTypesRoute,
  AuthenticatedSharedCoursesRoute: AuthenticatedSharedCoursesRoute,
  AuthenticatedStudyPlansRoute: AuthenticatedStudyPlansRoute,
  AuthenticatedTeachingAssignmentsRoute: AuthenticatedTeachingAssignmentsRoute,
  AuthenticatedTermsRoute: AuthenticatedTermsRoute,
  AuthenticatedTimeSlotTemplatesRoute: AuthenticatedTimeSlotTemplatesRoute,
  AuthenticatedTimeSlotsRoute: AuthenticatedTimeSlotsRoute,
  AuthenticatedUniversitiesRoute: AuthenticatedUniversitiesRoute,
  AuthenticatedUnresolvedSuggestionsRoute:
    AuthenticatedUnresolvedSuggestionsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedTimetableVersionIdRoute: AuthenticatedTimetableVersionIdRoute,
  AuthenticatedTimetableVersionIdPrintRoute:
    AuthenticatedTimetableVersionIdPrintRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyReportRoute: VerifyReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
