/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedUniversitiesRouteImport } from './routes/_authenticated/universities'
import { Route as AuthenticatedTimeSlotsRouteImport } from './routes/_authenticated/time-slots'
import { Route as AuthenticatedTermsRouteImport } from './routes/_authenticated/terms'
import { Route as AuthenticatedTeachingAssignmentsRouteImport } from './routes/_authenticated/teaching-assignments'
import { Route as AuthenticatedStudyPlansRouteImport } from './routes/_authenticated/study-plans'
import { Route as AuthenticatedSharedCoursesRouteImport } from './routes/_authenticated/shared-courses'
import { Route as AuthenticatedSessionTypesRouteImport } from './routes/_authenticated/session-types'
import { Route as AuthenticatedSectionsRouteImport } from './routes/_authenticated/sections'
import { Route as AuthenticatedSchedulingSettingsRouteImport } from './routes/_authenticated/scheduling-settings'
import { Route as AuthenticatedRoomsRouteImport } from './routes/_authenticated/rooms'
import { Route as AuthenticatedRoomTypesRouteImport } from './routes/_authenticated/room-types'
import { Route as AuthenticatedProgramsRouteImport } from './routes/_authenticated/programs'
import { Route as AuthenticatedMyCollegeRouteImport } from './routes/_authenticated/my-college'
import { Route as AuthenticatedInstructorsRouteImport } from './routes/_authenticated/instructors'
import { Route as AuthenticatedInstructorTypesRouteImport } from './routes/_authenticated/instructor-types'
import { Route as AuthenticatedDepartmentsRouteImport } from './routes/_authenticated/departments'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCoursesRouteImport } from './routes/_authenticated/courses'
import { Route as AuthenticatedCourseOfferingsRouteImport } from './routes/_authenticated/course-offerings'
import { Route as AuthenticatedCollegesRouteImport } from './routes/_authenticated/colleges'
import { Route as AuthenticatedBuildingsRouteImport } from './routes/_authenticated/buildings'
import { Route as AuthenticatedAvailabilityRouteImport } from './routes/_authenticated/availability'
import { Route as AuthenticatedAcademicCalendarRouteImport } from './routes/_authenticated/academic-calendar'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUniversitiesRoute =
  AuthenticatedUniversitiesRouteImport.update({
    id: '/universities',
    path: '/universities',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTimeSlotsRoute = AuthenticatedTimeSlotsRouteImport.update({
  id: '/time-slots',
  path: '/time-slots',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTermsRoute = AuthenticatedTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeachingAssignmentsRoute =
  AuthenticatedTeachingAssignmentsRouteImport.update({
    id: '/teaching-assignments',
    path: '/teaching-assignments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudyPlansRoute = AuthenticatedStudyPlansRouteImport.update({
  id: '/study-plans',
  path: '/study-plans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSharedCoursesRoute =
  AuthenticatedSharedCoursesRouteImport.update({
    id: '/shared-courses',
    path: '/shared-courses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSessionTypesRoute =
  AuthenticatedSessionTypesRouteImport.update({
    id: '/session-types',
    path: '/session-types',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSectionsRoute = AuthenticatedSectionsRouteImport.update({
  id: '/sections',
  path: '/sections',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSchedulingSettingsRoute =
  AuthenticatedSchedulingSettingsRouteImport.update({
    id: '/scheduling-settings',
    path: '/scheduling-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRoomsRoute = AuthenticatedRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoomTypesRoute = AuthenticatedRoomTypesRouteImport.update({
  id: '/room-types',
  path: '/room-types',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgramsRoute = AuthenticatedProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyCollegeRoute = AuthenticatedMyCollegeRouteImport.update({
  id: '/my-college',
  path: '/my-college',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInstructorsRoute =
  AuthenticatedInstructorsRouteImport.update({
    id: '/instructors',
    path: '/instructors',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstructorTypesRoute =
  AuthenticatedInstructorTypesRouteImport.update({
    id: '/instructor-types',
    path: '/instructor-types',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDepartmentsRoute =
  AuthenticatedDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoursesRoute = AuthenticatedCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCourseOfferingsRoute =
  AuthenticatedCourseOfferingsRouteImport.update({
    id: '/course-offerings',
    path: '/course-offerings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCollegesRoute = AuthenticatedCollegesRouteImport.update({
  id: '/colleges',
  path: '/colleges',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBuildingsRoute = AuthenticatedBuildingsRouteImport.update({
  id: '/buildings',
  path: '/buildings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAvailabilityRoute =
  AuthenticatedAvailabilityRouteImport.update({
    id: '/availability',
    path: '/availability',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcademicCalendarRoute =
  AuthenticatedAcademicCalendarRouteImport.update({
    id: '/academic-calendar',
    path: '/academic-calendar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/academic-calendar': typeof AuthenticatedAcademicCalendarRoute
  '/availability': typeof AuthenticatedAvailabilityRoute
  '/buildings': typeof AuthenticatedBuildingsRoute
  '/colleges': typeof AuthenticatedCollegesRoute
  '/course-offerings': typeof AuthenticatedCourseOfferingsRoute
  '/courses': typeof AuthenticatedCoursesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/instructor-types': typeof AuthenticatedInstructorTypesRoute
  '/instructors': typeof AuthenticatedInstructorsRoute
  '/my-college': typeof AuthenticatedMyCollegeRoute
  '/programs': typeof AuthenticatedProgramsRoute
  '/room-types': typeof AuthenticatedRoomTypesRoute
  '/rooms': typeof AuthenticatedRoomsRoute
  '/scheduling-settings': typeof AuthenticatedSchedulingSettingsRoute
  '/sections': typeof AuthenticatedSectionsRoute
  '/session-types': typeof AuthenticatedSessionTypesRoute
  '/shared-courses': typeof AuthenticatedSharedCoursesRoute
  '/study-plans': typeof AuthenticatedStudyPlansRoute
  '/teaching-assignments': typeof AuthenticatedTeachingAssignmentsRoute
  '/terms': typeof AuthenticatedTermsRoute
  '/time-slots': typeof AuthenticatedTimeSlotsRoute
  '/universities': typeof AuthenticatedUniversitiesRoute
  '/users': typeof AuthenticatedUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/academic-calendar': typeof AuthenticatedAcademicCalendarRoute
  '/availability': typeof AuthenticatedAvailabilityRoute
  '/buildings': typeof AuthenticatedBuildingsRoute
  '/colleges': typeof AuthenticatedCollegesRoute
  '/course-offerings': typeof AuthenticatedCourseOfferingsRoute
  '/courses': typeof AuthenticatedCoursesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/instructor-types': typeof AuthenticatedInstructorTypesRoute
  '/instructors': typeof AuthenticatedInstructorsRoute
  '/my-college': typeof AuthenticatedMyCollegeRoute
  '/programs': typeof AuthenticatedProgramsRoute
  '/room-types': typeof AuthenticatedRoomTypesRoute
  '/rooms': typeof AuthenticatedRoomsRoute
  '/scheduling-settings': typeof AuthenticatedSchedulingSettingsRoute
  '/sections': typeof AuthenticatedSectionsRoute
  '/session-types': typeof AuthenticatedSessionTypesRoute
  '/shared-courses': typeof AuthenticatedSharedCoursesRoute
  '/study-plans': typeof AuthenticatedStudyPlansRoute
  '/teaching-assignments': typeof AuthenticatedTeachingAssignmentsRoute
  '/terms': typeof AuthenticatedTermsRoute
  '/time-slots': typeof AuthenticatedTimeSlotsRoute
  '/universities': typeof AuthenticatedUniversitiesRoute
  '/users': typeof AuthenticatedUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/academic-calendar': typeof AuthenticatedAcademicCalendarRoute
  '/_authenticated/availability': typeof AuthenticatedAvailabilityRoute
  '/_authenticated/buildings': typeof AuthenticatedBuildingsRoute
  '/_authenticated/colleges': typeof AuthenticatedCollegesRoute
  '/_authenticated/course-offerings': typeof AuthenticatedCourseOfferingsRoute
  '/_authenticated/courses': typeof AuthenticatedCoursesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/departments': typeof AuthenticatedDepartmentsRoute
  '/_authenticated/instructor-types': typeof AuthenticatedInstructorTypesRoute
  '/_authenticated/instructors': typeof AuthenticatedInstructorsRoute
  '/_authenticated/my-college': typeof AuthenticatedMyCollegeRoute
  '/_authenticated/programs': typeof AuthenticatedProgramsRoute
  '/_authenticated/room-types': typeof AuthenticatedRoomTypesRoute
  '/_authenticated/rooms': typeof AuthenticatedRoomsRoute
  '/_authenticated/scheduling-settings': typeof AuthenticatedSchedulingSettingsRoute
  '/_authenticated/sections': typeof AuthenticatedSectionsRoute
  '/_authenticated/session-types': typeof AuthenticatedSessionTypesRoute
  '/_authenticated/shared-courses': typeof AuthenticatedSharedCoursesRoute
  '/_authenticated/study-plans': typeof AuthenticatedStudyPlansRoute
  '/_authenticated/teaching-assignments': typeof AuthenticatedTeachingAssignmentsRoute
  '/_authenticated/terms': typeof AuthenticatedTermsRoute
  '/_authenticated/time-slots': typeof AuthenticatedTimeSlotsRoute
  '/_authenticated/universities': typeof AuthenticatedUniversitiesRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/academic-calendar'
    | '/availability'
    | '/buildings'
    | '/colleges'
    | '/course-offerings'
    | '/courses'
    | '/dashboard'
    | '/departments'
    | '/instructor-types'
    | '/instructors'
    | '/my-college'
    | '/programs'
    | '/room-types'
    | '/rooms'
    | '/scheduling-settings'
    | '/sections'
    | '/session-types'
    | '/shared-courses'
    | '/study-plans'
    | '/teaching-assignments'
    | '/terms'
    | '/time-slots'
    | '/universities'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/academic-calendar'
    | '/availability'
    | '/buildings'
    | '/colleges'
    | '/course-offerings'
    | '/courses'
    | '/dashboard'
    | '/departments'
    | '/instructor-types'
    | '/instructors'
    | '/my-college'
    | '/programs'
    | '/room-types'
    | '/rooms'
    | '/scheduling-settings'
    | '/sections'
    | '/session-types'
    | '/shared-courses'
    | '/study-plans'
    | '/teaching-assignments'
    | '/terms'
    | '/time-slots'
    | '/universities'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/academic-calendar'
    | '/_authenticated/availability'
    | '/_authenticated/buildings'
    | '/_authenticated/colleges'
    | '/_authenticated/course-offerings'
    | '/_authenticated/courses'
    | '/_authenticated/dashboard'
    | '/_authenticated/departments'
    | '/_authenticated/instructor-types'
    | '/_authenticated/instructors'
    | '/_authenticated/my-college'
    | '/_authenticated/programs'
    | '/_authenticated/room-types'
    | '/_authenticated/rooms'
    | '/_authenticated/scheduling-settings'
    | '/_authenticated/sections'
    | '/_authenticated/session-types'
    | '/_authenticated/shared-courses'
    | '/_authenticated/study-plans'
    | '/_authenticated/teaching-assignments'
    | '/_authenticated/terms'
    | '/_authenticated/time-slots'
    | '/_authenticated/universities'
    | '/_authenticated/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/universities': {
      id: '/_authenticated/universities'
      path: '/universities'
      fullPath: '/universities'
      preLoaderRoute: typeof AuthenticatedUniversitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/time-slots': {
      id: '/_authenticated/time-slots'
      path: '/time-slots'
      fullPath: '/time-slots'
      preLoaderRoute: typeof AuthenticatedTimeSlotsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/terms': {
      id: '/_authenticated/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof AuthenticatedTermsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teaching-assignments': {
      id: '/_authenticated/teaching-assignments'
      path: '/teaching-assignments'
      fullPath: '/teaching-assignments'
      preLoaderRoute: typeof AuthenticatedTeachingAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/study-plans': {
      id: '/_authenticated/study-plans'
      path: '/study-plans'
      fullPath: '/study-plans'
      preLoaderRoute: typeof AuthenticatedStudyPlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shared-courses': {
      id: '/_authenticated/shared-courses'
      path: '/shared-courses'
      fullPath: '/shared-courses'
      preLoaderRoute: typeof AuthenticatedSharedCoursesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/session-types': {
      id: '/_authenticated/session-types'
      path: '/session-types'
      fullPath: '/session-types'
      preLoaderRoute: typeof AuthenticatedSessionTypesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sections': {
      id: '/_authenticated/sections'
      path: '/sections'
      fullPath: '/sections'
      preLoaderRoute: typeof AuthenticatedSectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scheduling-settings': {
      id: '/_authenticated/scheduling-settings'
      path: '/scheduling-settings'
      fullPath: '/scheduling-settings'
      preLoaderRoute: typeof AuthenticatedSchedulingSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rooms': {
      id: '/_authenticated/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AuthenticatedRoomsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/room-types': {
      id: '/_authenticated/room-types'
      path: '/room-types'
      fullPath: '/room-types'
      preLoaderRoute: typeof AuthenticatedRoomTypesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/programs': {
      id: '/_authenticated/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof AuthenticatedProgramsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-college': {
      id: '/_authenticated/my-college'
      path: '/my-college'
      fullPath: '/my-college'
      preLoaderRoute: typeof AuthenticatedMyCollegeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/instructors': {
      id: '/_authenticated/instructors'
      path: '/instructors'
      fullPath: '/instructors'
      preLoaderRoute: typeof AuthenticatedInstructorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/instructor-types': {
      id: '/_authenticated/instructor-types'
      path: '/instructor-types'
      fullPath: '/instructor-types'
      preLoaderRoute: typeof AuthenticatedInstructorTypesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/departments': {
      id: '/_authenticated/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AuthenticatedDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses': {
      id: '/_authenticated/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AuthenticatedCoursesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/course-offerings': {
      id: '/_authenticated/course-offerings'
      path: '/course-offerings'
      fullPath: '/course-offerings'
      preLoaderRoute: typeof AuthenticatedCourseOfferingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/colleges': {
      id: '/_authenticated/colleges'
      path: '/colleges'
      fullPath: '/colleges'
      preLoaderRoute: typeof AuthenticatedCollegesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buildings': {
      id: '/_authenticated/buildings'
      path: '/buildings'
      fullPath: '/buildings'
      preLoaderRoute: typeof AuthenticatedBuildingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/availability': {
      id: '/_authenticated/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AuthenticatedAvailabilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academic-calendar': {
      id: '/_authenticated/academic-calendar'
      path: '/academic-calendar'
      fullPath: '/academic-calendar'
      preLoaderRoute: typeof AuthenticatedAcademicCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAcademicCalendarRoute: typeof AuthenticatedAcademicCalendarRoute
  AuthenticatedAvailabilityRoute: typeof AuthenticatedAvailabilityRoute
  AuthenticatedBuildingsRoute: typeof AuthenticatedBuildingsRoute
  AuthenticatedCollegesRoute: typeof AuthenticatedCollegesRoute
  AuthenticatedCourseOfferingsRoute: typeof AuthenticatedCourseOfferingsRoute
  AuthenticatedCoursesRoute: typeof AuthenticatedCoursesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDepartmentsRoute: typeof AuthenticatedDepartmentsRoute
  AuthenticatedInstructorTypesRoute: typeof AuthenticatedInstructorTypesRoute
  AuthenticatedInstructorsRoute: typeof AuthenticatedInstructorsRoute
  AuthenticatedMyCollegeRoute: typeof AuthenticatedMyCollegeRoute
  AuthenticatedProgramsRoute: typeof AuthenticatedProgramsRoute
  AuthenticatedRoomTypesRoute: typeof AuthenticatedRoomTypesRoute
  AuthenticatedRoomsRoute: typeof AuthenticatedRoomsRoute
  AuthenticatedSchedulingSettingsRoute: typeof AuthenticatedSchedulingSettingsRoute
  AuthenticatedSectionsRoute: typeof AuthenticatedSectionsRoute
  AuthenticatedSessionTypesRoute: typeof AuthenticatedSessionTypesRoute
  AuthenticatedSharedCoursesRoute: typeof AuthenticatedSharedCoursesRoute
  AuthenticatedStudyPlansRoute: typeof AuthenticatedStudyPlansRoute
  AuthenticatedTeachingAssignmentsRoute: typeof AuthenticatedTeachingAssignmentsRoute
  AuthenticatedTermsRoute: typeof AuthenticatedTermsRoute
  AuthenticatedTimeSlotsRoute: typeof AuthenticatedTimeSlotsRoute
  AuthenticatedUniversitiesRoute: typeof AuthenticatedUniversitiesRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAcademicCalendarRoute: AuthenticatedAcademicCalendarRoute,
  AuthenticatedAvailabilityRoute: AuthenticatedAvailabilityRoute,
  AuthenticatedBuildingsRoute: AuthenticatedBuildingsRoute,
  AuthenticatedCollegesRoute: AuthenticatedCollegesRoute,
  AuthenticatedCourseOfferingsRoute: AuthenticatedCourseOfferingsRoute,
  AuthenticatedCoursesRoute: AuthenticatedCoursesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDepartmentsRoute: AuthenticatedDepartmentsRoute,
  AuthenticatedInstructorTypesRoute: AuthenticatedInstructorTypesRoute,
  AuthenticatedInstructorsRoute: AuthenticatedInstructorsRoute,
  AuthenticatedMyCollegeRoute: AuthenticatedMyCollegeRoute,
  AuthenticatedProgramsRoute: AuthenticatedProgramsRoute,
  AuthenticatedRoomTypesRoute: AuthenticatedRoomTypesRoute,
  AuthenticatedRoomsRoute: AuthenticatedRoomsRoute,
  AuthenticatedSchedulingSettingsRoute: AuthenticatedSchedulingSettingsRoute,
  AuthenticatedSectionsRoute: AuthenticatedSectionsRoute,
  AuthenticatedSessionTypesRoute: AuthenticatedSessionTypesRoute,
  AuthenticatedSharedCoursesRoute: AuthenticatedSharedCoursesRoute,
  AuthenticatedStudyPlansRoute: AuthenticatedStudyPlansRoute,
  AuthenticatedTeachingAssignmentsRoute: AuthenticatedTeachingAssignmentsRoute,
  AuthenticatedTermsRoute: AuthenticatedTermsRoute,
  AuthenticatedTimeSlotsRoute: AuthenticatedTimeSlotsRoute,
  AuthenticatedUniversitiesRoute: AuthenticatedUniversitiesRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
