// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { brokeredPreviewStorage } from "./previewAuthStorage";

// These two values identify the public Supabase API endpoint. The publishable key
// is intentionally browser-visible and remains protected by RLS. Server secrets
// such as SUPABASE_SERVICE_ROLE_KEY must never be added here.
const PUBLIC_SUPABASE_URL = "https://emzytxqkxjjhsivqxdiu.supabase.co";
const PUBLIC_SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtenl0eHFreGpqaHNpdnF4ZGl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA2MDEyOTYsImV4cCI6MjA5NjE3NzI5Nn0.aQFwWUa61Jeuj3758n4WFKlbLWQiVryIQLIdhaH5P7A";

function createSupabaseClient() {
  // Prefer deployment-provided values, but retain the checked-in public
  // endpoint so a missing build-time environment file cannot take down the UI.
  const SUPABASE_URL =
    import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL || PUBLIC_SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    process.env.SUPABASE_PUBLISHABLE_KEY ||
    PUBLIC_SUPABASE_PUBLISHABLE_KEY;

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
